AlgorithmStudy-Allumbus/codingtest_algorithm_study

Hongjoo/lv1/둘만의암호.py
Hongjoo/lv1/평균구하기.py
Hongjoo/lv1/푸드파이트대회.py
Hongjoo/lv2/행렬의곱.py

1.  [PGS] 둘만의 암호 / lv1 / 50분 / 2024.04.01
2. [PGS] 푸드 파이트 대회 / lv1 / 20분 / 2024.04.02
3. [PGS] 행렬의 곱 / lv2 / 30분/2024.04.07
4. [PGS] 평균 구하기 / lv1/ 2분/2024.04.07

hongjoo / 4월 1주차 / 4문제

---

Hongjoo/lv1/두개뽑아서더하기.py
Hongjoo/lv2/JadenCase문자열만들기.py
Hongjoo/lv2/뒤에있는큰수찾기.py
Hongjoo/lv2/숫자블록.py

#TIL(노션)
- [PGS] 두 개 뽑아서 더하기 / lv1 / 30분
- https://nostalgic-knife-ad0.notion.site/dc982c446f3e4840bcdf812267f54729?pvs=4
- [PGS] 숫자 블록 / lv2 / 실패
- https://nostalgic-knife-ad0.notion.site/21a858a2900c4f61b29397feddc3b268?pvs=4
- [PGS] 뒤에 있는 큰 수 찾기 / lv2 / 실패
- https://nostalgic-knife-ad0.notion.site/fef4457a86114694a83f4490648737c9?pvs=4
- [PGS] JadenCase 문자열 만들기 / lv2 / 실패
- https://nostalgic-knife-ad0.notion.site/JadenCase-4d8b55b5bd1243d194a4315d9dd544c1?pvs=4

Hongjoo /4월 2주차 /4문제

---

minjeong/BruteForce/2024-04-19-[백준]-#11047-동전0.py
minjeong/Combinatorics/2024-04-20-[백준]-#9375-패션왕신해빈.py
minjeong/DynamicProgramming/2024-04-17-[백준]-#1003-피보나치.py
minjeong/HashMap/2024-04-18-[백준]-#17219-비밀번호찾기.py

-> 푼 문제
- [백준 #1003. 피보나치 함수](https://www.acmicpc.net/problem/1003): DP 실버3
- [백준 #17219. 비밀번호 찾기](https://www.acmicpc.net/problem/17219): 해시테이블 실버4
-  [백준 #11047. 동전 0](https://www.acmicpc.net/problem/101104703): 그리디 실버4
-  [백준 #9375. 패션왕 신해빈](https://www.acmicpc.net/problem/9375): 조합론, 해시테이블 실버3
---
정리한 노션 링크: [노션](https://minggirokkk.notion.site/1003-e98a34cfbd914c47aa701f917805e55b?pvs=4)
$F0​=0, F1​=1, Fn+2​=Fn+1​+Fn​$
(0), 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987
**F(0) = 0이 1번 호출 `default`**
**F(1) = 0이 0번 호출, 1이 1번 호출 `default`**
**F(2) = 0이 1번 호출, 1이 1번 호출**
- **F(1) + F(0)** → 0이 1번 호출, 1이 한번 호출
**F(3) = 0이 1번 호출, 1이 2번 호출**
- F(2) + F(1) **⇒ F(1) + F(0) + F(1)** → 0이 1번 호출, 1이 2번 호출
**F(4)  = 0이 2번 호출, 1이 3번 …

Minjeong / 4월 3주차 / 4문제

---

learntosurf/Baekjoon/12_브루트 포스/1018.py
learntosurf/Baekjoon/12_브루트 포스/2798.py
learntosurf/Baekjoon/12_브루트 포스/2839.py

백준 단계별 문제풀기 12단계 "브루트포스" 완료
백준 1018번 체스판 다시 칠하기 문제가 너무 어려웠는데 혹시 풀어보신 분 계실까요..😮

Soomi Jeong / 5월 2주차 / 3문제 

---

YoonYn9915/Graph/2024-07-01-[백준]-#10026-적록색약.py
YoonYn9915/Graph/2024-07-01-[백준]-#4963-섬의 개수.py

> **제출한 코드**와 **TIL**은 꼭 작성해주기!
> 푼 문제
- [백준 #10026. 적록색약](https://www.acmicpc.net/problem/10026): 그래프 / 골드5
- [백준 #4396. 섬의 개수](https://www.acmicpc.net/problem/4396): 그래프 / 실버2
---
정리한 링크: (https://www.notion.so/8c6528b075434791a09bed32a0e35e32)
1. n을 input으로 받는다.
2. visited도 n x n 크기로 생성한 후 0으로 초기화해준다.
3. RGB 값을 담을 arr을 사용자의 입력값으로 생성한다.                                                                                arr = [list(input()) for _ in range(n)]
4. collections 라이브러리의 deque를 이용해 queue를 생성한다.
5. 적록색약이 아닌 경우와 적록색약인 경우로 나누어서 생각한다. 기본적으로는 두 경우 다 이중 for문을 돌며 모든 2차원 배열을 탐색하면서 방문하지 않은 노드에 대해 bfs를 진행한다. 적록색약인 경우는 R과 G를 구분하지 않기 때문에 시작 전 모든 노드를 순회하며 R을 G로 바꿔준다. (G를 R로 바꿔도 됌)
6. …

YoonYn9915 / 6월 5주차 / 2문제 

---

minjeong/DFSBFS/2024-06-29-[백준]-#14888-연산자끼워넣기.py
minjeong/Greedy/2024-06-26-[PGS]-#H-index.py
minjeong/HashMap/2024-06-27-[PGS]-전화번호목록.py
minjeong/Stack, Queue/2024-06-27-[Programmers]-기능개발.py

> **제출한 코드**와 **TIL**은 꼭 작성해주기!
> 푼 문제
- [프로그래머스 고득점kit > 정렬 > H-index](https://school.programmers.co.kr/learn/courses/30/lessons/42747): 정렬 / Level 2 (홍주 발제)
- [프로그래머스 고득점kit > 스택/큐 > 기능개발](https://school.programmers.co.kr/learn/courses/30/lessons/42586): 스택, 큐 / Level 2
- [프로그래머스 고득점kit > 해시 > 전화번호 목록](https://school.programmers.co.kr/learn/courses/30/lessons/42577#qna): 해시 / Level 2
- [백준 #14888. 연산자 끼워넣기](https://www.acmicpc.net/problem/14888): DFSBFS / 실버1
---
정리한 링크: [노션](https://minggirokkk.notion.site/3a93dbbd675444a4b1e5a46864de10fc?pvs=4)
스택을 이용했다.
1. 정답리스트 `answer`, 스택 리스트 `stack`, 기능 개발 개수 `feat_count`를 초기화한다.
2. 그 다음 총 기능 개수만큼 for loop를 반복하며 아래 과정을 수행한다.
1. `i` 번째마다 걸리는 날짜를 계산하여 `day` 에 저장한다. 
걸리는 날짜는 100에서 …

Minjeong / 6월 5주차 / 3문제

---

Hongjoo/lv2/배달.py
Hongjoo/백준/특정거리의도시찾기.py

> 푼 문제
- [백준 #18352. 특정 거리의 도시 찾기](https://www.acmicpc.net/problem/18352): BFS / 실버2
- [프로그래머스 # 배달](https://school.programmers.co.kr/learn/courses/30/lessons/12978#) : 다익스트라/lv2 
---
정리한 링크: (https://zaqquum01.notion.site/7a8925a410664f2ea09958f3c84659fb?pvs=4)
정리한 링크 : (https://zaqquum01.notion.site/832054aaf0e8415d84c3324bb831f159?pvs=4)

김홍주/ 7월 2주차 / 2개

---

minjeong/DFSBFS/2024-07-21-[백준]-#1260-DFS와BFS.py
minjeong/HashMap/2024-07-20-[PGS]-#오픈채팅방.py
minjeong/Recursion/2024-07-13-[PGS]-#괄호변환.py
minjeong/Stack, Queue/2024-07-19-[백준]-#9935-문자열폭발.py

> 푼 문제: 3문제 
- [BOJ #9935. 문자열폭발](https://www.acmicpc.net/problem/9935): 스택 / 골드4
- [PGS 2019 KAKAO BLIND RECRUIMENT 오픈채팅방](https://school.programmers.co.kr/learn/courses/30/lessons/42888): 해시맵 / Level 2
- [BOJ #1260. DFS와 BFS](https://www.acmicpc.net/problem/1260): 그래프 / 실버2
---
정리한 링크: ([바로가기](https://minggirokkk.notion.site/49b2dc9702534164b0a7a7716fb54d77?pvs=4))
1. 전체 문자열인 `s`, 폭발 문자열인 `bomb`, 스택으로 사용할 리스트인 `stack`, 폭발문자열의 길이만큼 스택을 pop해야 하기 때문에 폭발문자열의 길이인 `bomb_length`를 초기화한다.
2. `s`를 순회하면서 `stack`에 push한다. 
3. 이때 `stack`의 맨 마지막에서 `bomb_length` 길이를 문자열로 합친 값이 폭발문자열과 동일한 경우, 폭발문자열의 길이만큼 `stack`에서 pop한다.
4. 순회가 다 끝나면 `stack`에 값이 남아있는 경우에 `stack`을 문자열로 합친 값을 출력하고, `stack`에 아무것도 없는 경우 문제에서 주어진 ‘FRULA’를 출력한다.
```python
import sys
s = …
```

Minjeong / 7월 3주차 / 3문제

---

Hongjoo/lv1/로또의최고순위와최저순위.py
Hongjoo/lv2/다리를지나는트럭.py
Hongjoo/lv2/디펜스게임.py
Hongjoo/백준/특정거리의도시찾기2.py

> 푼 문제
- [프로그래머스 # 로또의 최고 순위와 최저 순위](https://school.programmers.co.kr/learn/courses/30/lessons/77484): 구현 / lv1
- [프로그래머스 #다리를 지나는 트럭](https://school.programmers.co.kr/learn/courses/30/lessons/42583): 구현/ lv2
- [프로그래머스 #디펜스 게임](https://school.programmers.co.kr/learn/courses/30/lessons/142085): 우선순위큐/lv2
---
정리한 링크: ([바로가기](https://zaqquum01.notion.site/cabf7200fcf642a58a7342defcd1f096?pvs=4))
정리한 링크: ([바로가기](https://zaqquum01.notion.site/4f42b1419a374c2097d31248f9205671?pvs=4))
정리한 링크: ([바로가기](https://zaqquum01.notion.site/704f9e09bc954cb39ffcae492aa08eaa?pvs=4)

김홍주/ 7월 4주차/ 3개

---

YoonYn9915/Graph/2024-08-05-[백준]-#18405-경쟁적 전염.py
YoonYn9915/math/2024-08-02-[백준]-#2745-진법 변환.py
YoonYn9915/recursion/2024-08-02-[백준]-#10870-피보나치 수 5.py
YoonYn9915/recursion/2024-08-02-[백준]-#27433-팩토리얼 2.py

> 푼 문제
- [백준 #2745. 진법 변환](https://www.acmicpc.net/problem/2745): 수학 / 브론즈2
- [백준 #27433. 팩토리얼 2](https://www.acmicpc.net/problem/27433): 재귀 / 브론즈5
- [백준 #10870. 피보나치 수 5](https://www.acmicpc.net/problem/10870): 재귀 / 브론즈2
- [백준 #18405. 경쟁적 전염](https://www.acmicpc.net/problem/18405): 그래프 / 골드5
---
정리한 링크: https://www.notion.so/7da0538ff8ea4b86b162e4b8300e966c?pvs=4
> 진법 변환은 숫자 N, 진수 B를 받아서 10 진법으로 계산한다.
아래와 같은 순서로 진행했다.
1. N과 B를 받는다.
2. 정답을 저장할 ans변수를 만든다.
3. 자릿수를 역순으로 나타낼 i를 만든다.
1. i는 자릿수를 역순으로 나타내며 맨 앞일때는 1, 다음은 2 이런식으로 진행
4. 수 N이 주어졌을 때, 수 N을 문자열로 받아서 반복문에 넣고, 각 문자를 돌면서 char형을 int형으로 바꾼후 정답을 계산한다.
1. ans = ans + int형으로 변환한 수 * B^(N의 길이 - i)
```
import sys
inp = sys.stdin.readline
arr = inp().split()
n = arr[0]
b = int(arr[1])
ans = 0
i = 1
length = len(n)
for …
```

YoonYn9915 / 7월5주차/ 4문제

---

Hongjoo/lv1/모의고사.py
Hongjoo/백준/감시피하기.py
Hongjoo/백준/경쟁적전염.py

> 푼 문제 : 
- [백준 #18045. 경쟁적 전염](https://www.acmicpc.net/problem/18405): BFS / 골드2
- [프로그래머스 #모의고사](https://school.programmers.co.kr/learn/courses/30/lessons/42840): 완전탐색/ lv1
- [백준 #18428. 감시피하기](https://www.acmicpc.net/problem/18428): 백트래킹 / 골드2
---
정리한 링크: ([바로가기](https://zaqquum01.notion.site/18045-86962555d006458794cc701b9e354a9b?pvs=4))
정리한 링크: ([바로가기](https://zaqquum01.notion.site/e192053e821344c1bc5bef653d4767f1?pvs=4))
정리한 링크: ([바로가기](https://zaqquum01.notion.site/18428-5cdf4f93362a4761a3c427c231240810?pvs=4))

김홍주/7월5주차/3문제

---

YoonYn9915/Graph/2024-08-12-[백준]-#16234-인구 이동.py
YoonYn9915/math/2024-08-12-[백준]-#2720-세탁소 사장 동혁.py
YoonYn9915/recursion/2024-08-12-[백준]-#1992-쿼드트리.py

> 푼 문제
- [백준 #16234. 인구 이동](https://www.acmicpc.net/problem/16234): 그래프 이론/ 골드4
- [백준 #2720. 세탁소 사장 동혁](https://www.acmicpc.net/problem/2720): 수학/ 브론즈3
- [백준 #1992. 쿼드트리](https://www.acmicpc.net/problem/1992): 재귀/ 실버1
---
정리한 링크: https://www.notion.so/1950141a72274f51ba5d50eefaa89282?pvs=4
이 문제는 그래프에서 **인접한 칸의 수를 모두 따져봐야** 하기 때문에  BFS로 풀어야 한다고 생각했다. 문제를 구현하기 앞서 아래와 같은 순서로 진행했다.
1. 입력값 받기
2. 2차원 배열을 돌며 인구 이동을 할 수 있는지 확인하기
1. 1. 인접한 나라
2. 2. 인접한 두 나라의 인구 차의 절댓값이 l이상 r이하
3. 인구 이동을 할 수 있으면 bfs로 그래프를 탐색하면서 인구 이동 나라의 개수와 인구의 총합을 구해서 새로운 인구를 구하기
4. 인구 이동을 한 날 구하기
```
import sys
#1. 입력값 받기
#2. 모든 배열을 돌며 인구이동 조건을 만족하는 나라가 있는지 확인. (1. 인접한 나라 2. 두 국가의 인구 차의 절댓값이 l이상 r이하)
#3. 인구 이동조건을 만족하는 나라가 있으면 bfs로 그래프를 탐색하면서 나라의 개수와 인구의 총합을 구해서 새로운 인구를 구해준다. …
```

YoonYn9915 / 8월1주차/ 3문제

---

minjeong/BruteForce/2024-08-15-[백준]-#30446-회문수.py
minjeong/DFSBFS/2024-08-12-[백준]-#16234-인구이동.py
minjeong/Greedy/2024-08-13-[백준]-#22993-서든어택3.py
minjeong/HashMap/2024-08-13-[백준]-#25239-학생별통화요금계산.py
minjeong/Simulation/2024-08-14-[백준]-#2223-금화.py

> 푼 문제: 5개
- [백준 #16234. 인구 이동](https://www.acmicpc.net/problem/16234): 그래프 / 골드4
- [백준 #25329. 학생별 통화 요금 계산](https://www.acmicpc.net/problem/25329): 해시 / 실버4
- [백준 #22993. 서든 어택3](https://www.acmicpc.net/problem/22993): 그리디 / 실버3
- [백준 #2223. 금화](https://www.acmicpc.net/problem/2223): 구현 / 실버3
- [백준 #30446. 회문수](https://www.acmicpc.net/problem/30446): 브루트포스 / 실버2
---
정리한 링크: ([바로가기](https://minjeong.oopy.io/465d037a-61ec-4a78-a19c-a552f295087a))
1. `N`, `L`, `R`을 입력받고 `N`개의 줄에서 각 나라의 인구수를 `nation` 리스트에 저장한다
2. **BFS 탐색과 연합 형성**:
- 매일 각 나라를 탐색하여, 인구 차이가 조건에 맞는 이웃 나라들과 연합을 형성한다.
- 연합을 형성하기 위해 BFS (너비 우선 탐색)를 사용한다. `BFS`는 한 나라에서 출발하여 인구 차이가 `L` 이상 `R` 이하인 이웃 나라들을 계속 탐색해 나가며, 연합 리스트를 나타내는 union 리스트에 추가한다.
3. **인구 이동**:
- 연합을 형성한 후, 연합이 2개 이상의 …

Minjeong / 8월 3주차 / 5문제

---

YoonYn9915/Graph/2024-08-27-[백준]-#14502-연구소.py
YoonYn9915/Graph/2024-09-09-[프로그래머스]-#60063-블록 이동하기.py
YoonYn9915/implementation/2024-09-02-[백준]-#20055-컨베이어 벨트 위의 로봇.py
YoonYn9915/implementation/2024-09-03-[백준]-#21610-마법사 상어와 비바라기.py

> 푼 문제
- [백준 #14502. 연구소](https://www.acmicpc.net/problem/14502): 그래프 / 골드4
- [백준 #20055. 컨베이어 벨트 위의 로봇](https://www.acmicpc.net/problem/1541): 구현 / 골드5
---
- [백준 #14502. 연구소](https://www.acmicpc.net/problem/14502): 그래프 / 골드4
정리한 링크: (https://www.notion.so/880dd9e2a52e4b77925d385b97da2295?pvs=4)
```
import sys
import copy
def bfs():
global arr, virusLocation,N,M, maxSafeAreaCount
copyArr = copy.deepcopy(arr)
dx = [0,0,1,-1]
dy = [1,-1,0,0]
queue = deque(virusLocation)
while queue:
startRow,startCol = queue.popleft()
for i in range(4):
row = startRow + dx[i]
col = startCol + dy[i]
if 0<=row<N and 0<=col<M and copyArr[row][col] == 0:
#바이러스 확산
copyArr[row][col] = 2
#방문처리
queue.append((row,col))
#안전영역 세기
safeAreaCount = 0
for i in range(N):
for j in range(M):
if …
```

YoonYn9915 / 8월 5주차 / 2문제

---

Hongjoo/lv0/평행.py
Hongjoo/lv2/압축.py

> 푼 문제
- [프로그래머스  #압축](https://school.programmers.co.kr/learn/courses/30/lessons/17684\): 구현 / lv2
- [프로그래머스 #평행](https://school.programmers.co.kr/learn/courses/30/lessons/120875#): 구현 / lv0
---
정리한 링크: ([바로가기](https://zaqquum01.notion.site/6044cdc9c3d245a6b36a7cdd62fd7151?pvs=4))
정리한 링크: ([바로가기](https://zaqquum01.notion.site/10a9899f253f809db9ddc115767b0845?pvs=4))

Hongjoo/9월 2-3주차/2문제

---

minjeong/DFSBFS/2024-09-24-[PGS]-#모음사전.py
minjeong/DynamicProgramming/2024-09-23-[백준]-#14501-퇴사.py
minjeong/Greedy/2024-09-29-[PGS]-#단속카메라.py

> 푼 문제
- [백준 #14501. 퇴사](https://www.acmicpc.net/problem/14501): DP / 실버3
- [PGS #모음사전](https://school.programmers.co.kr/learn/courses/30/lessons/84512): 완전탐색 / Level2
- [PGS #단속카메라](https://school.programmers.co.kr/learn/courses/30/lessons/42884): 그리디 / Level 3
---
1. 초기화를 진행한다.
남은 날짜 `N`을 입력받는다. 걸리는 기간과 상담 금액은 각각 `t`, `p` 리스트에 입력받아 저장한다. `N+1`의 크기만큼 `dp`를 0으로 초기화한다.
2. 1부터 `N+1`까지 아래 과정을 반복하며 `dp`를 채운다.
1. 현재 날짜(`i`)에 해당하는 시간과 금액을 각각 `time`, `pay`에 저장한다.
2. 현재 날짜로부터 상담을 완료하는 날을 `day` 변수에 저장한다. 이는 `i`(현재) + `time - 1`로 구할 수 있다.
3. 기본 `dp` 조건인 점화식을 설정해주어 최댓값을 저장하도록 업데이트한다.
`dp[i] = max(dp[i], dp[i-1])`
4. 만약 `day`가 남은 날짜인 `N`보다 작을 경우, `day`에 해당하는 `dp`의 값도 점화식에 따라 업데이트해준다. 
`dp[day] = max(dp[day], dp[i - 1] + pay)`
3. `dp`의 가장 마지막 요소가 곧 최대 수익이므로 이를 출력한다.
```python …
```

Minjeong / 9월 4주차 / 3문제

---

Hongjoo/백준/병사배치하기.py
Hongjoo/백준/퇴사.py

> 푼 문제
- [백준 #14501. 퇴사](https://www.acmicpc.net/problem/14501): DP/ 실버
- [백준 #18353. 병사 배치하기](https://www.acmicpc.net/problem/18353): DP/ 실버
---
정리한 링크: ([바로가기](https://zaqquum01.notion.site/75dbaed05a2446ce95a737f160040e96?pvs=4))
> #dp[1~n+1]: 누적 소득 리스트 #역순으로 for 문 
1. dp[n+1] = 0 초기화
2. 상담 가능 여부 확인 : 
- `if  i + T[i]  < N+1` . 불가능  ⇒ dp[i] = dp[i+1]
3. 상담 가능 한 경우 ,  현재 price + 바로 담 상담 price VS 내일 상담 price 비교 
1. 점화식 : `dp[i] = max(P[i] + dp[i+T_i] , P[i+1])`
```python
"""
#dp : 1, 중복 , 최적 부분  -> memorize 
goal :최대 이익 
input : time , price , 0 
#1. 역순으로 N ~ 1 (퇴사일 N+1)
for i in range(N , 0 , -1)
#2-1 상담 가능 여부 (1)
if i + T_i <= N 이면 -> 가능
if not -> false (0) 
리스트 dp :  
dp[i] = 현재 price + 바로 담 상담 price VS 내일 상담 price
dp[i] = max(P[i] + dp[i+T_i] , P[i+1])
"""
import sys
n = …
```

Hongjoo/9월 4주차 /2문제

---

YoonYn9915/dp/2024-10-07-[백준]-#13301-타일 장식물.py
YoonYn9915/dp/2024-10-07-[백준]-#18353-병사 배치하기.py

> 푼 문제
- [백준 #18353. 병사 배치하기](https://www.acmicpc.net/problem/18353): dp/ 실버2
- [백준 #13301. 타일 장식물](https://www.acmicpc.net/problem/13301): dp / 실버5
---
정리한 링크: https://www.notion.so/1181eff69e9e80d7b175df1fd183b250
1. N과 배열 arr을 입력받습니다.
2. dp 리스트를 1로 초기화하여, 각 인덱스에서 끝나는 가장 긴 증가하는 부분 수열의 길이를 저장합니다.
3. sort(arr, dp) 함수에서 배열을 탐색하며, 이전 값과 비교해 더 긴 증가하는 부분 수열을 찾습니다.
4. 각 인덱스에서 끝나는 가장 긴 증가하는 부분 수열의 길이를 dp 리스트에 업데이트합니다.
5. dp 리스트에서 최대값을 찾고, 배열의 전체 크기에서 그 값을 뺀 결과를 출력합니다.
```
def sort(arr,dp):
global N
for i in range(1,N,1):
for j in range(i-1,-1,-1):
if arr[j] > arr[i]:
dp[i] = max(dp[i],dp[j]+1)
N = int(input())
arr = list(map(int,input().split()))
dp = [1] * N
sort(arr, dp)
print(N-max(dp))
```
---
1. 사용자로부터 n을 입력받습니다.
2. dp 리스트를 초기화합니다.
3. n > 5일 경우, dp 리스트를 확장합니다.
4. 일반적인 경우 수식을 통해 ans 값을 …

YoonYn9915 / 10월 1주차 / 2문제

---

Hongjoo/백준/계단 오르기.py
Hongjoo/백준/정수삼각형.py

> 푼 문제
- [백준 #1932. 정수삼각형](https://www.acmicpc.net/problem/1932): DynamicPrograming/ 실버1
-[백준 #2579.계단 오르기](https://www.acmicpc.net/problem/2579): DynamicPrograming / 실버3
---
정리한 링크: ([바로가기](https://zaqquum01.notion.site/1932-1189899f253f80a68bf5f41bfcd99a3e?pvs=4))
>  top-dowm 방향으로 더할때 , 각 경로에서 요소들의 누적합을 리스트 dp 에 저장하기
1.  2중 for 문
2. 각 숫자의 위치에서 이전 stage 에서 올 수 있는 두 값 중에 더 큰 값을 선택해 누적 합을 계산한다. 
- 점화식
(1) 맨 left: `idx = 0`   인 경우
=> `dp[stage][0] =dp[stage-1][0] + graph[stage][0]`
(2) 맨 right : `idx = -1` 인 경우
=> dp[stage][-1] =dp[stage-1][-1] + graph[stage][-1]
(3) 가운데 `idx : 1~ state-1`
- ↙️ 우측 대각선 방향 합  : `dp[stage-1][idx] + graph[stage][idx-1]`
- ↘️ 좌측 대각선 방향 합 : , `dp[stage-1][idx] + graph[stage][idx]`
위 두 값을 비교해서 더 큰 값을 `dp[stage][idx]` 에 저장하기
=> …

HONGJOO/10월 2주차 / 2문제

---

minjeong/Backtracking/2024-10-15-[백준]-#2661-좋은수열.py
minjeong/DynamicProgramming/2024-10-14-[백준]-#15483-최소편집.py
minjeong/Simulation/2024-10-17-[백준]-#10992-별찍기17.py

> 푼 문제
- [백준 #15433. 최소 편집](https://www.acmicpc.net/problem/15433): DP / 골드3
- [백준 #2661. 좋은 수열](https://www.acmicpc.net/problem/2661): 백트래킹 / 골드4
- [백준 #10992. 별찍기 17](https://www.acmicpc.net/problem/15433): 구현 / 브론즈3
---
정리한 링크: ([바로가기](https://minjeong.oopy.io/11fdded9-d6ea-80a3-b74c-c5381dc5438f))
> 💡 **점화식**
- 행과 열에 해당하는 문자가 서로 같다면, 왼쪽 위( ↘ )에 해당하는 수를 그대로 대입
⇒ `dp[i][j] = dp[i-1][j-1]`
- 행과 열에 해당하는 문자가 서로 다르다면, 왼쪽(삽입), 위쪽(삭제), 왼쪽 위↘(교체)에 해당하는 수 중에서 가장 작은 수에 1을 더해 대입
⇒  `dp[i][j] = min(dp[i-1][j], min(dp[i][j-1], dp[i-1][j-1])) + 1`
> 플로우
1. 두 문자열 `A`와 `B`를 입력받는다.
- `A`와 `B`의 길이에 각각 1을 더한 크기의 2차원 배열 `dp`를 초기화한다. 이 배열은 **부분 문자열 간의 최소 편집 횟수**를 저장한다.
1. `dp` 배열의 초기값을 저장한다.
1. 첫 번째 행과 첫 번째 열은 **빈 문자열(공집합)**에서 다른 문자열로 변환하는 데 필요한 비용을 저장한다.
2. `dp` 배열의 **행과 열을 …

Minjeong / 10월 3주차 / 3문제

---

Hongjoo/기타/못생긴수.py
Hongjoo/백준/계단 오르기.py
Hongjoo/백준/최소편집.py

> 푼 문제
- [백준 #15483. 최소편집](https://www.acmicpc.net/problem/15483): DP/ Gold4
- [정올 #1318. 못생긴수](https://jungol.co.kr/problem/1318): DP/ Gold3
---
정리한 링크: ([바로가기](https://zaqquum01.notion.site/15483-11f9899f253f80e7b619d7dbf6feadbe?pvs=4))
1. 2차 배열 (len(before) , len(after) dp  리스트 생성 및 초기화
1. **Y축 (before) -> X 축 after**
2. i=0 .or j=0 인 경우, 다음과 같이 초기화 한다
2. 최소 편집 거리 점화식 
- 해당하는 단어가 아닌 **charater**끼리 비교
1. B[i] == A[j] # 두 char 가 같을 때 → 유지
`dp[i][j] = dp[i-1][j-1]`  :#대각선
2. B[i] == A[j] # 두 char 가 다를 때 → 추가, 제거, 교체 중 1개 중 선택
`dp[i][j] = min(dp[i][j-1], dp[i-1][j], dp[i-1][j-1]) +1`   # 추가, 제거, 교체 
중 최소 거리 +1
3. 최종 최소 편집 거리
`dp[-1][-1]`
```python
import sys
before =[0]+ list(sys.stdin.readline())[:-1]
after = [0] + list(sys.stdin.readline())[:-1]
dp = [[0 for _ …
```

Hongjoo/ 10월 3주차 / 2문제

---

Hongjoo/lv1/성격유형검사하기l.py

> 푼 문제
- [프로그래머스 #성격유형검사하기](https://school.programmers.co.kr/learn/courses/30/lessons/118666): 구현/ LV1
- [프로그래머스 #문자열을 정수로 바꾸](https://school.programmers.co.kr/learn/courses/30/lessons/12925): 구현/ LV1
---
정리한 링크: ([바로가기](https://zaqquum01.notion.site/12d9899f253f809b8837e34ebde1e899?pvs=4))
1. 문항 별 유형과 값을 리스트에 업로드 및 더하기
2. 짝을 이루는 성격 유형 별로 계산하
```python
"""
1 - R,T 
2 - C,F
3,- J , M
4 - A, N
=> 7 : +3N , 6 : +2N , 5 : +1N  4: 0  , 3 : +A , 2: +2A , 1 : + 3A (비동의)
"""
def solution(survey, choices):
answer = ''
vote = list()
for i in range(len(survey)) : 
a = survey[i][0] ; b = survey[i][1] #  비동의 , 동의
target = ''
tmp = choices[i]-4
if tmp > 0 : # 양수 -> 동의
target = b 
elif tmp < 0 : # 음수 -> 비동의
target = a 
tmp = tmp * (-1)
else : # tmp == 0
continue
if len(vote) == …
```

Honjoo / 10월 4주차 / 2문제

---

minjeong/BinarySearch/2024-10-26-[백준]-#1072-게임.py
minjeong/DFSBFS/2024-10-24-[백준]-#16173-점프왕쩰리(Small).py
minjeong/Graph/2024-10-26-[백준]-#2252-줄세우기.py
minjeong/Graph/위상정렬_알고리즘.py
minjeong/String/2024-10-20-[백준]-#13163-닉네임에_갓_붙이기.py
minjeong/String/2024-10-23-[백준]-#1755-숫자놀이.py

> 푼 문제
- [백준 #13163. 닉네임에 갓 붙이기](https://www.acmicpc.net/problem/13163): 문자열 / 브론즈3
- [백준 #1755. 숫자놀이 ](https://www.acmicpc.net/problem/1755): 문자열 / 실버4
- [백준 #16173. 점프왕 쩰리 (Small) ](https://www.acmicpc.net/problem/16173): DFSBFS / 실버4
- [백준 #1072. 게임](https://www.acmicpc.net/problem/1072): 이분탐색 / 실버3
- [백준 #2252. 줄 세우기](https://www.acmicpc.net/problem/2252): 위상정렬,그래프 / 골드3
---
- 문자열을 공백을 기준으로 split 하기
- split하여 구분된 것 중에 1번째부터 다시 문자열로 합친 후 맨 앞에 `god` 합치기
```python
n = int(input())
for i in range(n):
name = input().split()
god = 'god' + ''.join(name[1:])
print(god)
```
---
1. 초기화 작업을 진행한다. 
1. 숫자를 영어로 변환하기 위한 리스트 `english`를 준비한다. 
이 리스트는 숫자 0부터 9까지의 영단어를 저장한 리스트이다. 인덱스로 구분하여 저장한다. 예를 들어 0번째 인덱스에는 `zero`, 1번째 인덱스에는 `one`, … 9번째 인덱스에는 …

Minjeong / 10월 4주차 / 5개

---

YoonYn9915/Graph/2024-10-28-[백준]-#15683-감시.py
YoonYn9915/Graph/2024-10-28-[백준]-#3665-최종 순위.py

> 푼 문제
- [백준 #15683. 감시](https://www.acmicpc.net/problem/2579): dfs/bfs / 골드 3/ 실패
- [백준 #3665. 최종 순위](https://www.acmicpc.net/problem/2775): 그래프 / 골드 1 /실패
---
정리한 링크: 작성 중
1. 입력 및 초기 설정
입력 받기: 사무실의 크기(N, M)와 각 칸의 정보를 포함하는 그래프를 입력받습니다.
CCTV 목록 생성: 그래프를 탐색하여 CCTV의 위치와 종류를 cctv_list에 저장합니다.
초기값 설정: 사각지대의 최솟값을 찾기 위해 answer를 큰 값(10억)으로 초기화합니다.
2. CCTV 감시 영역 탐색
DFS 함수 호출: dfs 함수를 호출하여 CCTV의 감시 영역을 탐색합니다. 현재 깊이(depth)는 0으로 시작합니다.
3. 재귀적 탐색 (DFS)
종료 조건: 모든 CCTV를 탐색한 경우, count_zero 함수를 호출하여 사각지대의 개수를 세고, answer를 갱신합니다.
CCTV 정보 복사: 현재 CCTV의 정보를 깊은 복사하여 graph_copy를 만듭니다.
감시 방향 탐색: 현재 CCTV의 가능한 모든 방향으로 감시 영역을 탐색합니다.
watch 함수를 호출하여 해당 방향으로 감시 영역을 표시합니다.
다음 CCTV를 재귀적으로 탐색하기 위해 dfs를 다시 호출합니다.
CCTV의 방향을 변경하기 위해 graph_copy를 다시 원본 그래프로 복사합니다.
4. CCTV 감시 영역 …

YoonYn9915 / 10월 4주차 / 2문제 

---

YoonYn9915/Graph/2024-11-04-[백준]-#14567-선수 과목.py
YoonYn9915/math/2024-11-04-[백준]-#1004-어린 왕자.py

> 푼 문제
- [백준 #14567. 선수 과목](https://www.acmicpc.net/problem/14567): 그래프 / 골드 5
- [백준 #1004. 어린 왕자](https://www.acmicpc.net/problem/1004): 수학 / 실버 3
---
1. 그래프 및 진입차수 설정
사용자로부터 노드(과목) 수 N과 간선(선수 과목 관계) 수 M을 입력받습니다.
graph: 각 노드의 연결 관계를 저장하는 인접 리스트입니다. 각 노드는 자신과 연결된 다른 노드를 저장합니다.
inDegree: 각 노드의 진입차수를 저장하는 리스트입니다. 각 노드가 몇 개의 선수 과목을 가져야 하는지 기록합니다.
2. 간선 정보 입력
M개의 간선을 입력받아, 각 간선 (A, B)에서 A가 B의 선수 과목임을 표현합니다.
graph[A].append(B)를 통해 A 노드에서 B 노드로 이동 가능하도록 설정합니다.
inDegree[B] += 1을 통해 B 노드의 진입차수를 1 증가시켜줍니다.
3. 위상 정렬 수행 (topology_sort 함수)
result: 각 노드별 최소 학기 수를 기록하는 리스트로, 초기값은 -1로 설정하여 초기 상태임을 나타냅니다.
queue: 진입차수가 0인 노드들을 저장하여 순차적으로 처리합니다.
queue가 빌 때까지 반복하면서 다음을 수행합니다:
queue에서 now 노드를 꺼내어 현재 노드와 연결된 모든 노드를 탐색합니다.
연결된 각 노드의 진입차수를 1씩 감소시키고, 진입차수가 0이 되면 해당 …

YoonYn9915 / 11월 1주차 / 2문제

---

Hongjoo/lv2/숫자의표현.py
Hongjoo/백준/문자열교환.py
Hongjoo/백준/부분합.py

- 이번주는 two pointer 와 이와 비슷한 Sliding window 알고리즘 위주로 문제를 풀었다. 다양한 유형의 문제를 풀었던 지난 시간보다는 동일 유형을 풀면서 해당 two pointer 계열의 알고리즘 문제의 해결방법에 대해선 감을 잡은 것 같다. 특히 연속하는 숫자의 나열을 이용하는 문제의 경우 대다수  two pointer로 접근하다는 것을 배웠다. 
> 푼 문제
- [백준 #1522. 문자열교환](https://www.acmicpc.net/problem/1541): 투 포인터 / 실버
- [백준 #1806. 부분합](https://www.acmicpc.net/problem/1806)]: 투 포인터 / 골드
- [프로그래머스. 숫자의 표현](https://school.programmers.co.kr/learn/courses/30/lessons/12924#)] : 투포인터/ lv2
---
정리한 링크: ([바로가기](https://zaqquum01.notion.site/1522-1429899f253f80dfbd05f60b2ccb3ea7?pvs=4))
> 
goal : a,b 만 있는 문자열 중 a를 모두 연속으로 만들기 위한 최소 교환 횟수 찾기
- 교환 후 **연속된 a 문자열 길이 = 총 a 의 개수**
- 즉, a 의 개수와 동일한 길이의 연속된 문자열을 슬라이싱 하고 , 슬라이싱 한 문자열 내부에 있는 b와 외부에 있는 a와 교환하면 a 가 연속되게 된다 .
- 이때 **교환횟수는 슬라이싱 문자열 내부에 …

Hongjoo/11월 3주차 / 3문제

---

minjeong/Backtracking/2024-12-01-[백준]-#17825-주사위윷놀이.py
minjeong/DynamicProgramming/2024-12-02-[백준]-#11066-파일합치기.py
minjeong/Simulation/2024-12-02-[백준]-#3190-뱀.py
minjeong/Simulation/2024-12-04-[백준]-#13335-트럭.py
minjeong/Stack, Queue/2024-12-06-[백준]-#14713-앵무새.py

- 구현 문제가 있으면 항상 냅다 브루트포스로 구현했는데 이 문제를 통해서 ‘자료구조’를 이용하며 푸는 것이 중요하다는 것을 알게 되었다. 뱀의 길이를 큐로 관리하는 것이 새로웠다.
- 단순한 큐 문제에서도 `deque`가 있는지 없는지 판단하는 `any`를 이용할 수 있다는 것을 알게 되었다.
- 이번 한 주는 바빠서 많이 못 풀었지만 큼직큼직한 문제들을 통해서 문제를 푸는 과정을 설계하는 것이나 새로운 논리를 배우는 것이 많아 의미가 있었던 한 주였던 것 같다.
> 푼 문제
- [백준 #17825. 주사위 윷놀이](https://www.acmicpc.net/problem/17825): 백트래킹 / 골드2
- [백준 #11066. 파일 합치기](https://www.acmicpc.net/problem/11066): DP / 골드3
- [백준 #3190. 뱀](https://www.acmicpc.net/problem/3190): 구현, 자료구조 / 골드4
- [백준 #13335. 트럭](https://www.acmicpc.net/problem/13335): 구현, 자료구조 / 실버1
- [백준 #14713. 앵무새](https://www.acmicpc.net/problem/14713): 자료구조 / 실버2
---
정리한 링크: ([바로가기](https://minjeong.oopy.io/14fdded9-d6ea-8072-a5e2-c4b59eccc767))
1. **그래프 생성**
- 각 칸의 연결 정보를 배열로 저장하여 …

Minjeong / 12월 1주차 / 5문제

---

Hongjoo/lv2/JadenCase문자열만들기_재도전.py
Hongjoo/백준/뱀.py
Hongjoo/백준/트럭.py
Hongjoo/백준/평범한배낭.py

- 오래만에 복잡한 구현 문제들을 풀어보았다.  시간을 충분히 들이면 모두 풀 수 있는 였지만 문제를 읽고, 이해한 후 코드 까지 구현하는데 시간이 많이 소모된다는 것을 깨달았다. 다음 부터는 좀 더 간단하게 코드를 작성할 수 있는 구현 아이디어를 생각하도록 노력하고자 한다. 
> 푼 문제
- [[백준 #3190뱀]](https://www.acmicpc.net/problem/3190):구현/ Gold4
- [백준 #13335 트럭](https://www.acmicpc.net/problem/13335): 구현/ Silver1
- [프로그래머스 #JadenCase](https://school.programmers.co.kr/learn/courses/30/lessons/12951): 구현/ lv2
---
정리한 링크: ([바로가기](https://zaqquum01.notion.site/3190-1559899f253f8050b814ce978ffb0a1b?pvs=4))
1. 입력 값 변수에 할당(field구축 , 뱀의 방향 정보)
- field : N+2
빈 곳 = 0
벽, 뱀의 위치 = -1 
사과 = 1
로 값 채우기
1. 업데이트된 head 위치의 field  상황 확인하기
- head의 위치가 =-1 (벽, 본인) 이면 → game over
- 그 외는 ( 사과 , 빈곳)은  사과 존재 여부에 따라
- 사과가 없으면(head=0) 꼬리 이동 , head 이동
- 사과 있으면(head=1) 꼬리 유지 , head  이동
```python
import sys
from …
```

Hongjoo/12월 1주차 / 3문제

---

Hongjoo/lv2/오픈채팅방.py
Hongjoo/백준/테트로미노.py

- 이번 주 과제 문제를 풀면서  먼저 문제 유형 파악한 후 문제에 접근해야 한다는 점을 깨달았다.  DFS로 하면 간단하게 해결될 부분을 냅다 구현 문제 풀듯이 접근하여 문제풀이 시간을 너무 오래걸렸고,  작성한 코드도 다른 코드에 비해 시간 복잡도는 줄었지만 코드 길이가 너무 비효율 적이었던 것도 반성 해야할 부분인 듯 하다. 
- 또한 요즘 문제 풀이 개수를 줄이면서 DFS, BFS 와 같이 이전에 공부한 내용도 휘발되는 듯 하다.  담주 부터는 문제 개수를 더 늘리면서 코테 감을 잊지 않도록 하자. 
> 과제 : 백준 #14500 테트로미노
- [백준 #14500 테트로미노](https://www.acmicpc.net/problem/14500): 구현,DFS/ Gold4
- [프로그래머스 # 오픈채팅방](https://school.programmers.co.kr/learn/courses/30/lessons/42888): 구현/ lv2
---
정리한 링크: ([바로가기](https://zaqquum01.notion.site/14500-15c9899f253f8018ab55ef732e9202a7?pvs=4))
1. NxM 형태의 필드와 그 위의 정수값을 graph 로 정의한다. 
2. graph 내 모든 칸을 한 칸씩 순회한다. 
3. 해당 칸을 기준(절대 좌표 `row ,col` )으로 19가지 테트로미노 중 최대 정수의 합을 구한다. 
이때 특정 칸 기준에서 상대 좌표로 각 테트로미노 위의 정수값을 파악,계산한다. …

Hongjoo / 12월 2주차 / 2문제

---

minjeong/DFSBFS/2024-12-16-[백준]-#2206-벽부수고이동하기.py
minjeong/DFSBFS/2024-12-21-[백준]-#13460-구슬탈출2.py
minjeong/DynamicProgramming/2024-12-20-[백준]-#11727-2xn타일링2.py
minjeong/Greedy/2024-12-20-[백준]-#1026-보물.py
minjeong/Greedy/2024-12-20-[백준]-#2217-로프.py

- 이번에는 최대한 문제 유형을 골고루 풀어보려고 해보았다. 그래서 그런지 골고루 헷갈렸다..ㅋㅋㅋㅋ 
- **DP나 그리디** 문제는 순전히 아이디어의 싸움이었는데 한번 아이디어가 안 떠오르면 계속 안 떠오르는 것 같다. 그래서 나름대로 예외경우도 생각해보고, 문제를 제대로 이해하는 것이 중요한 것 같다. 
- **BFS** 유형은 난이도가 있는 것이다보니까 새로운 접근법을 알게 되는 문제들이었다. `[벽 부수고 이동하기] `문제의 경우에는 visited 리스트를 3차원으로 관리하는 것이 신선했다. wall부분을 나누어 2개의 최단경로로 관리했다.  `[구슬탈출] `문제는 visited 리스트를 처음에 초기화해놓지 않고 방문할 때마다 방문한 구슬의 위치를 추가하는 식으로 상태를 관리했다. 방문 로직 처리를 이렇게 처리하는 방식이 신선하고 앞으로 풀 때 참고해야겠다고 생각이 들었다. 
- 문제를 풀 때 내 치명적인 실수가 무엇인지 알게 되었다. 나는 문제를 너무 대충 읽는다!! 그래서 `0`이나 `O`와 같은 문자를 착각하기도 하고, 문제를 제대로 이해 안 하고 접근하기도 했다. 이런 부분은 반성하고 문제를 온전히 이해하는데에 시간을 더 써야 할 것 같다. 
> 푼 문제
- [백준 #2206. 벽 부수고 이동하기 ](https://www.acmicpc.net/problem/2206): BFS / 골드3
- [백준 #11727. 2xn 타일링 …

Minjeong / 12월 3주차 / 5문제

---

minjeong/Greedy/2024-12-23-[백준]-#1700-멀티탭스케줄링.py
minjeong/Greedy/2024-12-25-[백준]-#1931-회의실배정.py
minjeong/Greedy/2024-12-27-[백준]-#1789-수들의합.py

1. 이번 주에는 그리디 유형을 풀었다. 그리디도 DP처럼 아이디어 싸움인 것 같다. `멀티탭 스케줄링`은 앞으로 사용되지 않을 기기를 먼저 뽑는 것이 핵심이었고, `회의실 배정`은 회의가 끝나는 시간으로 정렬하는 것이 핵심이었다. 이렇게 아이디어를 생각해내는 것 자체는 일반 문제를 푸는 것처럼 단순하지만 이를 코드로 구현하기 위해서 많은 연습이 필요할 것 같다.
2. `lambda`를 이용한 정렬의 문법은 자꾸 까먹어서 자주자주 봐야 할 것 같다.
> 푼 문제
- [백준 #1700. 멀티탭 스케줄링](https://www.acmicpc.net/problem/1700): 그리디 / 골드1
- [백준 #1931. 회의실 배정](https://www.acmicpc.net/problem/1931): 그리디 / 골드5
- [백준 #1789. 수들의 합](https://www.acmicpc.net/problem/1789): 그리디 / 실버5
---
정리한 링크: ([바로가기](https://minjeong.oopy.io/165dded9-d6ea-80b9-9855-c04e072a4d70))
1. **입력 받기**
- `N` (멀티탭 구멍 수), `K` (전기용품 사용 횟수)를 입력받는다.
- `items`에 전기용품 사용 순서를 저장한다.
3. **초기 설정**
- `multitap` : 현재 멀티탭에 꽂힌 전기용품을 저장하는 리스트
- `cnt` : 플러그를 뽑은 횟수를 기록하는 변수
4. **전기용품 사용 순서대로 멀티탭 처리** …

Minjeong / 12월 4주차 / 3문제

---

learntosurf/Data Structures/2025-01-11-[BOJ]-#10773-제로.py
learntosurf/Data Structures/2025-01-11-[BOJ]-#2164-카드2.py
learntosurf/Greedy/2024-12-22-[BOJ]-#1700-멀티탭스케줄링.py
learntosurf/Greedy/2025-01-11-[ETC]-Q1-모험가길드.py
learntosurf/Greedy/2025-01-11-[ETC]-Q2-곱하기혹은더하기.py
learntosurf/Greedy/2025-01-11-[ETC]-Q3-문자열뒤집기.py

- 1,2월에 알고리즘 이론 공부, 문제풀이 꾸준히 열심히 하기!!!!! 
- 스터디 잘 참여하기, 과제 놓치지 않기 
- <이것이 코딩테스트다> 책 유형별로 뽀개기 + 공부한 유형 백준에서도 풀기
- 매일 1문제 이상씩 풀기  
- 이번주는 몰아 풀었지만 다음주부터는 미리미리.. 
> 푼 문제 
- <이것이 코딩테스트다> Q1. 모험가 길드: 그리디 / ●○○ 
- <이것이 코딩테스트다> Q2. 곱하기 혹은 더하기: 그리디 / ●○○
- [백준 #1439.뒤집기](https://www.acmicpc.net/problem/1439): 그리디 / 실버5
- [백준 #10773.제로](https://www.acmicpc.net/problem/10773): 스택, 큐 / 실버4
- [백준 #2164.카드2](https://www.acmicpc.net/problem/2164): 스택, 큐 / 실버4
---
정리한 링크: [바로가기](https://learntosurf.notion.site/CH03-11-17881c5c217880948655de8558f26f68?pvs=4)
**<문제>** 
- 공포도가 X인 모험가는 반드시 X명 이상으로 구성한 모험가 그룹에 참여해야 여행을 떠날 수 있도록 규정
- N명의 모험가에 대한 정보가 주어졌을 때, 여행을 떠날 수 있는 그룹 수의 **최댓값** 출력
- 모든 모험가를 특정한 그룹에 넣을 필요 없음
**<접근법>** 
- **최대한 많은 그룹 수를 만드는 방법은, 최소한의 인원으로만 그룹을 구성하는 것**
- 모든 모험가들이 전부 그룹화 될 필요는 없으므로, 그룹 결성이 …

Learntosurf / 1월 2주차 / 5문제 

---

YoonYn9915/implementation/2025-01-11-[프로그래머스]-요격 시스템.py
YoonYn9915/implementation/2025-01-11-[프로그래머스]-자물쇠와 열쇠.py
YoonYn9915/implementation/2025-01-11-[프로그래머스]-표 병합.py

- 이번 주에는 카카오 코딩 테스트에서 나온 구현 문제를 풀어보았다. 리스트의 크기를 의도적으로 늘리거나 리스트를 회전시키는 등 리스트를 다뤄 문제를 푸는 여러 기법을 복습해 볼 수 있었던 것 같다.
> 푼 문제
- [프로그래머스 표 병합](https://school.programmers.co.kr/learn/courses/30/lessons/150366): 구현 / level 3
- [프로그래머스 자물쇠와 열쇠](https://school.programmers.co.kr/learn/courses/30/lessons/60059): 구현 / level 3
- [프로그래머스 요격 시스템](https://school.programmers.co.kr/learn/courses/30/lessons/181188): 구현 / level 2
---
정리한 링크: (바로가기)
1. 초기화
표 구성 (graph)
graph는 각 셀의 부모를 추적하는 50x50 크기의 2차원 배열로, 초기에는 (i, j)로 설정됩니다.
값 저장 (value)
각 셀의 값을 저장하는 50x50 크기의 2차원 배열로, 초기값은 "EMPTY"로 설정됩니다.
2. 명령어 처리
각 명령어에 따라 아래와 같이 동작합니다:
a. UPDATE 명령
a-1. 부모 셀(graph[r][c])을 찾아 해당 부모 셀의 값을 업데이트합니다.
a-2. 표 전체에서 value1 값을 가진 모든 셀을 찾아 value2로 변경합니다.
b. MERGE 명령
(r1, c1)과 (r2, c2) …

YoonYn9915 / 1월 2주차 / 3문제

---

Hongjoo/백준/곱셈.py
Hongjoo/백준/공통부분문자열.py
Hongjoo/백준/받아쓰기.py

- 이번주 최종 프로젝트를 시작해서 코테 문제에 소홀했으며 , 점점 남은 골드 레벨 문제들이 힌트 없이는 풀기 어려워지고 있다. 
코테 이론을 다시 한번 복습해야 될 것 같다. 
> 푼 문제
- [백준 #5582. 공통부분문자열](https://www.acmicpc.net/problem/5582): DP / 골드5
- [백준 #20548. 받아쓰기](https://www.acmicpc.net/problem/20548): DP / 골드5
- [백준 #1629.곱샘](https://www.acmicpc.net/problem/1629): Divide_Conquer / 실버1
---
정리한 링크: ([바로가기](https://zaqquum01.notion.site/5582-17a9899f253f808ba44dfb9b2149f460?pvs=4))
1. LCS저장할 dp 리스트 생성 
2. Longest common substring
1. 문자열 A, B 각각 한 글자씩 비교
2. 같으면 → lcs[i-1][j-1] (대각선) +1
3. 다르면 → 0 
4. 반복
3. longest commong substring 출력
⇒ **문자가 다를 경우,  0 초기화를 진행하여**  꼭 dp 의 마지막 depth가 결과를 의미하지 않음
```python
"""
https://www.acmicpc.net/problem/5582
LCSubstring 특징
1. 무조건 "연속된" 공통 문자열 -> 한번이라도 다르면 dp =0로 초기화, …
```

Hongjoo/1월 3주차 /3문제

---

minjeong/BinarySearch/2025-01-22-[백준]-#18114-블랙프라이데이.py
minjeong/Simulation/2025-01-25-[백준]-#1138-한줄로서기.py
minjeong/Simulation/2025-01-25-[백준]-#5365-생일.py
minjeong/Stack, Queue/2025-01-25-[백준]-#2161-카드1.py
minjeong/TwoPointer_SlidingWindow/2025-01-20-[백준]-#1253-좋다.py

- 이번 주는 **투 포인터/이분탐색 유형이랑 구현 유형** 문제를 풀면서 진짜 머리를 좀 굴렸던 한 주였다. 😅 특히 "**`좋다`**" 문제를 풀 때는 음수나 자기 자신을 포함하는 경우를 놓쳐서 시행착오를 겪었는데, 그 과정을 통해 예외 처리의 중요성을 다시 한번 깨달았다. "**`블랙 프라이데이`**" 문제에서는 1개, 2개, 3개 조합을 따로 나눠서 생각하며 문제를 구조적으로 접근하는 연습을 할 수 있었다.
- 구현 유형 문제 중 "**`한 줄로 서기`**" 문제는 처음부터 정렬을 사용할 필요 없이 "**배치**"를 해가며 풀 수도 있다는 것도 알게 되었다. 이렇게 접근하는 게 그리디인 것도 알게 되었는데, **다음 주에는 그리디 유형을 좀 더 풀어보면서 그리디의 감을 좀 더 익혀야 할 것 같다.**
> 푼 문제
- [백준 #1253. 좋다](https://www.acmicpc.net/problem/1253): 투포인터 / 골드4
- [백준 #18114. 블랙 프라이데이](https://www.acmicpc.net/problem/18114): 투포인터 / 골드5
- [백준 #2161. 카드1](https://www.acmicpc.net/problem/2161): 구현, 자료구조 / 실버5
- [백준 #5365. 생일](https://www.acmicpc.net/problem/5365): 구현, 문자열 / 실버5
- [백준 #1138. 한 줄로 서기](https://www.acmicpc.net/problem/1138): 구현, 그리디 / 실버2
---
정리한 …

Minjeong / 1월 4주차 / 5문제

---

Hongjoo/백준/보석도둑.py
Hongjoo/백준/블랙프라이데이.py
Hongjoo/백준/좋다.py

- 이번 푼 문제들은 내가 제시한 풀이는 모두 시간 초과가 나서 더 어려웠던 것 같다. 그냥 틀리면 반례라도 생각해볼텐데, 시간초과는 접근 방식 통채로 뒤엎어야 하는 상황이다 보니 더 그렇게 느낀 것 같다. 
앞으로 문제 풀이 작성할때, 시간 복잡도도 챙겨서 정리해봐야겠다. 
> 푼 문제
- [백준 #1253. 좋은수](https://www.acmicpc.net/problem/1253): 투포인터, 이진탐색 / 골드5
- [백준 #18114. 블랙프라이데이](https://www.acmicpc.net/problem/18114): 투포인터,완전탐색 / 골드5
- [백준 #1202. 보석도둑](https://www.acmicpc.net/problem/1202): 그리디 / 골드2
---
정리한 링크: ([바로가기](https://zaqquum01.notion.site/1253-1819899f253f804bae66cf40ac7b5b93?pvs=4))
투 포인터
- left 와 right 가 각각 target을 가르킨다.
- target 값보다 합이 같으면 → 정답
- target 값보다 합이 작으면 → left 포인터 우측 이동
- target 값보다 합이 크면  → right 포인터 좌측 이동
```python
import sys
def check_good(j , current) :
for right in range(1,) :
for left in range(0,right) :
print(f" {board[right]} + …
```

Hongjoo/1월 4주차/3문제

---

minjeong/Dijkstra/2025-02-01-[백준]-#1238-파티.py
minjeong/Dijkstra/2025-02-01-[백준]-#4485-녹색옷입은애가젤다지.py
minjeong/Graph/2025-02-01-[백준]-#1238-파티.py
minjeong/Graph/2025-02-01-[백준]-#4485-녹색옷입은애가젤다지.py
minjeong/Greedy/2025-01-29-[백준]-#1439-뒤집기.py
minjeong/Greedy/2025-01-29-[백준]-#1946-신입사원.py
minjeong/Greedy/2025-01-30-[백준]-#10610-30.py
minjeong/Greedy/2025-01-30-[백준]-#1202-보석도둑.py
minjeong/Simulation/2025-01-26-[백준]-#2477-참외밭.py
minjeong/Simulation/2025-01-31-[백준]-#1475-방번호.py

- `신입 사원`, `30`, `보석 도둑` 문제를 통해 정렬, 우선순위 큐 활용과 조건문 최적화의 필요성을 느꼈다. `파티`와 `젤다` 문제에서는 다익스트라 알고리즘에 대해 풀어보게 되었는데, 다익스트라 개념을 이해하고 다시 복습할 수 있는 계기가 되었다.
- 그리디와 그래프 유형이 약한 것 같아서 이 유형들을 좀 연습해야 할 것 같다.
> 푼 문제
- [백준 #2477. 참외밭](https://www.acmicpc.net/problem/2477): 구현 / 실버2
- [백준 #1439. 뒤집기](https://www.acmicpc.net/problem/1439): 그리디 / 실버5
- [백준 #1946. 신입 사원 ](https://www.acmicpc.net/problem/1946): 구현 / 실버1
- [백준 #10610. 30](https://www.acmicpc.net/problem/10610): 그리디 / 실버4
- [백준 #1202. 보석 도둑](https://www.acmicpc.net/problem/1202): 그리디 / 골드2
- [백준  #1475. 방 번호](https://www.acmicpc.net/problem/1475): 구현 / 실버5
- [백준 #1238. 파티](https://www.acmicpc.net/problem/1238): 그래프, 다익스트라 / 골드3
- [백준 #4485. 녹색 옷 입은 애가 …

Minjeong / 1월 5주차 / 8문제

---

YoonYn9915/Graph/2024-02-01-[백준]-#1058-친구.py
YoonYn9915/Graph/2024-02-01[백준]-#1238-파티.py
YoonYn9915/Graph/2024-02-01[백준]-#4485-녹색 옷 입은 애가 젤다지.py

- 이번주는 다익스트라와 플로이드 와샬 알고리즘에 관련된 문제를 풀었다. 다익스트라에 관련된 발제, 과제문제가 전부 시간제한이 1초라 우선순위 큐를 사용한 다익스트라를 구현해야 했는데, 파이썬에서 우선순위 큐를 사용하는 방법을 몰라서 헤맸던 것 같다. 오랫만에 관련 문제를 풀어봐서 낯설었고 잘 풀지 못했는데 다시 복습해봐야 겠다.
> 푼 문제
- [백준 #1238. 파티](https://www.acmicpc.net/problem/1238): 그래프, 다익스트라 / 골드3
- [백준 #4485. 녹색 옷 입은 애가 젤다지?](https://www.acmicpc.net/problem/4485): 그래프, 다익스트라 / 골드4
- [백준 #1058. 친구](https://www.acmicpc.net/problem/1058): 투 포인터 / 실버 2
---
정리한 링크: (바로가기)
```python
import heapq
def dijkstra(s):
D = [float('inf')] * (N+1)
D[s] = 0
q = []
heapq.heappush(q, (0, s))
while q:
dist, now = heapq.heappop(q)
if D[now] >= dist:
for v, val in city[now]:
if dist + val < D[v]:
D[v] = dist + val
heapq.heappush(q, (dist + val, v))
return D
N, M, X = map(int, input().split())
city = [[] for _ in …
```

YoonYn9915 /1월 5주차/3문제

---

minjeong/Simulation/2025-02-10-[백준]-#20057-마법사상어와토네이도.py
minjeong/Simulation/2025-02-14-[백준]-#20056-마법사상어와파이어볼.py

- 이번 주에 급하게 처리해야할 게 쌓여서 많이 풀지 못했다... (아마 2월 내내 참여가 어려울 수도 있을 것 같긴 하다.. 이번 주도.. 과제문제까지만 해서 내겠습니다ㅜㅜ) 그래도 코테 푸는 습관을 계속 들여야 하는데 한 번 놓치니까 계속 놓치는 것 같다. 
- 이번 주 발제 문제는 복잡한 구현 문제를 푸는 것이었다. 문제를 이해하는 것도 시간이 걸리지만 무엇보다 '코드로 옮기는 것'이 어려웠다. 이런 문제일수록 조건들을 하나하나 정리를 해야 할 것 같다. 그냥 많이 풀어봐야 할 것 같다. 
- 또 동시에 구현 문제는 정말 다양한 코드가 있는 것 같다. 그래서 다른 분들의 코드가 어떻게 다를지 궁금하기도 하다.
> 푼 문제
- [백준 #20057. 마법사 상어와 토네이도](https://www.acmicpc.net/problem/20057): 구현 / 골드3
- [백준 #20056. 마법사 상어와 파이어볼](https://www.acmicpc.net/problem/20056): 구현 / 골드4
---
정리한 링크: ([바로가기](https://minjeong.oopy.io/196dded9-d6ea-806d-aebb-fafd20194182))
1. **입력 처리**
- `N`과 `grid`(모래 격자)를 입력받는다.
- 토네이도의 시작 위치를 `(N//2, N//2)`로 설정한다.
2. **모래 이동 비율 정의**
- `left` 방향을 기준으로 모래가 흩날리는 비율을 리스트로 저장한다.
- `right`, `down`, …

Minjeong / 2월 2주차 / 2문제

---

learntosurf/Graph Traversal/2025-01-27-[BOJ]-#1238-파티.py
learntosurf/Graph Traversal/2025-02-15-[BOJ]-#4485-녹색옷입은애가젤다지?.py
learntosurf/Greedy/2025-02-03-[BOJ]-#1202-보석도둑.py
learntosurf/Implementation/2025-02-10-[BOJ]-#20057-마법사상어와토네이도.py
learntosurf/Implementation/2025-02-15-[BOJ]-#19638-센티와마법의뿅망치.py

- 1-2월에 알고리즘 문제풀이에 집중하려고 했었는데 공부를 많이 못하고 습관을 한번 놓친 이후로 회복하지 못했던것같아서 아쉽다. (쌓여가는 벌금..) 스터디를 참여하면서 느낀건 스터디에서 어려운 문제를 푸니 평상시에 난이도가 더 낮은 문제들을 많이 풀면서 알고리즘 공부를 해야겠다였는데 그러지 못했던 것 같아서 반성하게 됐다. 
- 이번주에는 밀렸던 발제, 과제 문제들을 풀었다. 어려운 문제들을 한번에 푸니까 쉽지 않았다. 급하게 푸느라 TIL을 작성하지 못했고, 끝까지 맞는 풀이를 못 낸 문제도 있다. 특히 최근 몇주차 발제 문제들은 더 어렵게 느껴졌던 것 같아서 꼭 정리를 다시 해봐야할 것 같다. 
- 다음주는 미리미리 조금씩 풀고, 챌린지 주제 문제들도 풀어보는것을 목표로. 
- [백준 #1202.마법사 상어와 토네이도](https://www.acmicpc.net/problem/1202): 구현 / 골드3
- [백준 #19638.센티와 마법의 뿅망치](https://www.acmicpc.net/problem/19638): 구현 / 실버1
- [백준 #1238.파티](https://www.acmicpc.net/problem/1238): 그래프 / 골드2
- [백준 #1202.보석도둑](https://www.acmicpc.net/problem/1202): 그리디 / 골드3
- [백준 #4485.녹색 옷 입은 애가 젤다지?](https://www.acmicpc.net/problem/1238): 그래프 / 골드4
---
```python
import sys 
N …
```

Learntosurf / 2월 2주차 / 5문제 

---

Hongjoo/백준/A2B.py
Hongjoo/백준/마법사상어와토네이도.py
Hongjoo/백준/센티와마법의뿅망치.py

- 이번 발제 문제인 "마법사 상어와 토네이도"문제를 통해 구현 문제가 어려우면 얼만큼 어려워 질 수 있는지 알게 해주었다. 담 주 부터는 매일 코테 문제를 풀 수 있도록 노력하겠다. 
> 푼 문제
- [백준 #20057. 마법사 상어와 토네이도](https://www.acmicpc.net/problem/20057): 구현 / 골드3
- [백준 #. 19638, 센티와 마법의 뿅망치](https://www.acmicpc.net/problem/19638): heap / 실버1
- [백준 #16953. A->B](https://www.acmicpc.net/problem/16953):  그래프/ 실버2
---
정리한 링크: [(바로가기](https://zaqquum01.notion.site/BOJ-20057-19b9899f253f8038856aca59d1d53203?pvs=4))
```python
"""
#20057. 마법사 상어와 토네이도
https://www.acmicpc.net/problem/20057
"""
delta = [(0, -1), (1, 0), (0, 1), (-1, 0)]
def rotate_90(proportion):
new_proportion = list(reversed(list(zip(*proportion))))
return new_proportion
p = [[0, 0, 0.02, 0, 0], [0, 0.1, 0.07, 0.01, 0], [0.05, 0, 0, 0, 0], [0, 0.1, 0.07, …
```

Hongjoo / 2월 2주차 /3문제 

---

minjeong/DynamicProgramming/2025-02-17-[백준]-#2169-로봇조종하기.py
minjeong/DynamicProgramming/2025-02-22-[백준]-#1520-내리막길.py

- 이번 주도 정신없어서 많이 풀지는 못했다..! 다음 주도 그럴 것 같다.. 3월부터 다시 시작할 예정이다.
- DP 문제와 DFS 문제가 합쳐진 문제를 풀면서 이런 식으로 내가 알던 알고리즘 개념이 묶일 수 있다는 것을 알게 되었다.
> 푼 문제
- [백준 #2169. 로봇 조종하기](https://www.acmicpc.net/problem/2169): DP / 골드2
- [백준 #1520. 내리막길](https://www.acmicpc.net/problem/1520): DP / 골드3
---
정리한 링크: (바로가기)
```python
import sys
N, M = map(int, input().split())
nums = []
for _ in range(N):
nums.append(list(map(int, input().split())))
dp = [[0] * M for _ in range(N)]
dp[0][0] = nums[0][0]
for j in range(1, M):
dp[0][j] = dp[0][j - 1] + nums[0][j]
for i in range(1, N):
left_prefix_sum = [0] * M  # 왼쪽 누적합
right_prefix_sum = [0] * M  # 오른쪽 누적합
left_prefix_sum[0] = dp[i-1][0] + nums[i][0]
for j in range(1, M):
left_prefix_sum[j] = …
```

Minjeong / 2월 3주차 / 2문제

---

YoonYn9915/dp/2025-02-22-[백준]-#1010-다리 놓기.py
YoonYn9915/dp/2025-02-22-[백준]-#1520-내리막길.py
YoonYn9915/dp/2025-02-22-[백준]-#2169-로봇 조종하기.py

- 이번 주는 발제 문제와 과제 문제로 dp 문제를 풀어보았다. 발제 문제는 dp 배열을 두 개 설정하고 각각 왼쪽, 오른쪽 방향에서 오는 최대 가치를 저장한 후 마지막으로 두 배열을 비교하여 더 큰 가치를 저장하는 '점화식' 코드가 인상깊었다. 과제 문제는 문제의 시간복잡도를 만족하기 위해 dfs와 dp를 융합하여 푸는 것이었는데 이론적으로는 어떻게 풀지 알고있었는데 메모리 초과를 해결하지 못해서 실패했다. 전반적으로 수준 높은 문제를 풀게 된 한 주였다.
> 푼 문제
- [백준 #2169. 로봇 조종하기](https://www.acmicpc.net/problem/2169): DP / 골드 2
- [백준 #1520. 내리막 길](https://www.acmicpc.net/problem/1541): DP / 골드 3
- [백준 #1010. 다리 놓기](https://www.acmicpc.net/problem/1541): DP /  실버5
---
정리한 링크: https://purple-jury-c2d.notion.site/19c1eff69e9e80818cf0c75b2b8f4c1b?pvs=4
1. 입력 받기
2. 첫 번째 행의 최대 가치 계산
첫 번째 행의 값들은 왼쪽 방향에서의 값만 누적 할 수 있다.
3. 두 번째 행부터 마지막 행까지 최대 가치 계산
각 행(i)에서 값을 갱신하는 두 개의 리스트 dp1, dp2를 생성.
dp1과 dp2를 순차적으로 갱신하면서 최적의 값을 저장.
왼쪽에서 오는 경우 (dp1)
dp1[j] = …

YoonYn9915/ 2월 3주차/ 3개

---

_WeeklyChallenges/W13-[Union-Find]/Assignment_BOJ_1717_집합의표현.py
minjeong/Heap/2025-03-08-[백준]-#11279-최대힙.py
minjeong/Heap/2025-03-08-[백준]-#11286-절댓값힙.py
minjeong/Heap/2025-03-08-[백준]-#1927-최소힙.py
minjeong/UnionFind/2025-03-03-[백준]-#1717-집합의표현.py
minjeong/UnionFind/2025-03-03-[백준]-#1976-여행가자.py

- 이번 주는 정신없는 한 주였지만, 발제를 맡게 되면서 다시 놓고 있던 코테 공부를 시작할 수 있었다.
> 푼 문제
- [백준 #1976. 여행 가자](https://www.acmicpc.net/problem/1976): 유니온파인드 /  골드4
- [백준 #1717. 집합의 표현](https://www.acmicpc.net/problem/1717): 유니온파인드 /  골드5
- [백준 #1927. 최소 힙](https://www.acmicpc.net/problem/1927): 자료구조, 힙 / 실버2
- [백준 #11279. 최대 힙](https://www.acmicpc.net/problem/11279): 자료구조, 힙 / 실버2
- [백준 #11286. 절댓값 힙](https://www.acmicpc.net/problem/11286): 자료구조, 힙 / 실버1
---
정리한 링크: (바로가기)
1. **입력 및 초기화**
- 도시의 개수 `n`과 여행 계획에 포함된 도시 수 `m`을 입력받는다.
- 각 도시는 처음에 자기 자신을 대표 노드로 가지도록 `parent` 배열을 초기화한다.
2. **그래프 연결 정보 처리**
- `n`개의 줄에 걸쳐 도시 간 연결 정보를 입력받는다.
- 각 행에서 값이 1이면 두 도시가 연결되어 있으므로, `union` 연산을 수행하여 하나의 집합으로 합친다.
3. **유니온 파인드 연산 구현**
- `find(a)` …

Minjeong / 3월 1주차 / 5문제

---

Hongjoo/백준/내리막길.py
Hongjoo/백준/로봇조종하기.py
Hongjoo/백준/마법사상어와파이어볼.py

- 최종 플젝이 드디어 마무리가 되었다. 상반기 지원이 얼마 남지 않은 만큼 담주부터 꼭 코테를 꾸준하게 풀 수 있도록 하자
> 푼 문제
- [백준 #2169. 로봇 조종하기](https://www.acmicpc.net/problem/2169): DP/ 골드2
- [백준 #20056. 마법사 상어와 파이어볼](https://www.acmicpc.net/problem/20056): 구현/ 골드4
- [백준 #1520. 내리막길](https://www.acmicpc.net/problem/1520): DP/ 골드3
---
정리한 링크: (바로가기)
```python
"""
https://www.acmicpc.net/problem/1520
"""
import sys
#0. 맵 (N,M) 칸 별 탐사 가치 설정
N , M = map(int,input().split()) # y,x 
fields =list()
for n in range(N) :
fields.append(list(map(int, input().split())))
dp = [[0 for _ in range(M)] for k in range(N)]
left2right = [[0 for _ in range(M)] for k in range(N)]
right2left = [[0 for _ in range(M)] for k in range(N)]
#3.탐색 가능  (1)left2 right <-/ (2) right2left <- 
for m in range(M) : …
```

Hongjoo/2월 4주차 / 3문제

---

YoonYn9915/dp/2025-03-15-[백준]-#2281-데스노트.py
YoonYn9915/dp/2025-03-15-[백준]-#2342-Dance Dance Revolution.py
YoonYn9915/dp/2025-03-15-[백준]-#2579-계단 오르기.py

- 이번 주는 DP 관련 문제를 풀었다. 발제 문제는 DP 유형이라는 것을 알고있음에도 무엇을 저장해야 할지, 점화식은 어떻게 작성해야 하는지 어떻게 풀어야 할지 감이 오지 않았다. 왼발의 위치, 오른발의 위치, 사용하는 힘 이렇게 3가지를 저장하는 3차원 배열을 사용해야 한다는 힌트를 듣고 감이 왔다. 더 많은 문제를 풀어보고 연습해야 겠다.
> 푼 문제
- [백준 #2342. Dance Dance Revolution](https://www.acmicpc.net/problem/2342): DP / 골드 3
- [백준 #2281. 데스노트](https://www.acmicpc.net/problem/2281): DP / 골드 3
- [백준 #2579. 계단 오르기](https://www.acmicpc.net/problem/2579): DP / 실버 3
---
정리한 링크: (바로가기)
1. 입력 및 초기 설정
2. 이동 비용 계산 함수 (get_add) 정의
이동 비용 규칙:
현재 k == 0 (처음 움직이는 경우): lr == 0이면 0, 그렇지 않으면 2
같은 위치 (k == lr): 비용 1
인접한 위치 (|k - lr| == 1 또는 |k - lr| == 3): 비용 3
나머지 경우: 비용 4
3. 입력 처리
move = list(map(int, input().split())): 입력된 움직임을 리스트로 저장.
만약 이동이 없다면 0을 출력하고 종료.
4. DP 테이블 초기화 …

YoonYn9915/ 3월 2주차/ 3문제

---

YoonYn9915/dp/2025-03-22-[백준]-#2193-이친수.py
YoonYn9915/dp/2025-03-22-[백준]-#2293-동전 1.py
YoonYn9915/dp/2025-03-22-[백준]-#2294-동전 2.py

- 이번 주는 DP 문제를 위주로 풀어보았다. 동전 1 문제에서 동전 조합 문제를 DP를 사용하여 풀어야 한다는 것은 이해했으나 DP 배열에 무엇을 저장해야 하는지 헷갈려서 힌트를 보고 말았다. 동전 2 문제의 경우는 동전 1과 비슷해서 어렵지 않게 풀 수 있었는데,  이번 문제는 DP 알고리즘 자체가 어렵다기보다는 문제의 조건(0.5초, 4MB)를 지키기 까다로웠던 것 같다. 
> 푼 문제
- [백준 #2293. 동전 1](https://www.acmicpc.net/problem/2293): DP / 골드 4
- [백준 #2294. 동전 2](https://www.acmicpc.net/problem/2294): DP / 골드 5
- [백준 #2193. 이친수](https://www.acmicpc.net/problem/2193): DP / 실버 3
---
정리한 링크: (바로가기)
1. 입력 처리
사용자로부터 n과 k를 입력받는다.
2. 동전 목록 및 DP 테이블 초기화
3. 동전 입력 받기
4. 초기 상태 설정
dp[0] = 1은 "아무 동전도 사용하지 않고 0원을 만드는 방법은 한 가지라는 의미"
5. DP 계산 (동전 조합의 경우의 수)
동전 c를 하나씩 꺼내서 현재 동전 c를 사용하여 만들 수 있는 금액 갱신
dp[i] += dp[i - c]의 의미:
현재 금액 i를 만들 때, "동전 c를 추가로 사용하여 만들 수 있는 경우의 수"를 기존 dp[i]에 더함.
즉, dp[i - c]는 "현재 동전 c를 포함했을 때 만들 …

YoonYn9915/ 3월 3주차/ 3문제

---

Hongjoo/백준/수열.py
Hongjoo/백준/피보나치비스무리한수열.py

- 이번 스킬 체크에도 LV2의 벽을 넘지 못했다. 문제 푸는 속도가 느린데 이게 문제를 적게 풀어서 문제인 것 같다. 이번 달은 꼭 LV2의 벽을 넘도록 하자 
> 푼 문제
- [백준 #2259. 수열](https://www.acmicpc.net/problem/2259): 슬라이딩윈도우 / 실버3
- [백준 #2468. 안전영역 ](https://www.acmicpc.net/problem/2468): 구현 / 실버1
- [백준 #14495. 피보나치비스무리한수열](https://www.acmicpc.net/problem/14495): DP / 실버5
---
정리한 링크: ([바로가기](https://zaqquum01.notion.site/BOJ-2259-1cb9899f253f80af9254efe74bd6fbd0?pvs=4))
1. temp 리스트 입력 받기
- window size =k , N  : 날짜
2. window 범위에 해당하는 리스트 합 중 최대값 구하기
- next_window = 이전 window - 앞 + 뒤
=> sliding winodw을 통해 window 내 맨앞과 맨 뒤 값만 구해서 더하고 빼면 범위내 총합 구할 수 있다.
```python
"""
-연속된 날짜의 온도 합 중 최대값 출력 = goal
- sum(temp[s:e]) 같은 한번씩 슬라이딩으로 합을 구하면 시간 초과 발생
- window 범위 내 start 와 end 포인트 값을 빼고, 더하는 식으로 전체 합 구하기
1. temp 리스트 …
```

HONGJOO/4월 1주차 /3문제 

---

Hongjoo/백준/로봇조종하기.py
_MonthlyChallenges/DASHBOARD.md
_MonthlyChallenges/scoreboard.json

- 최종 플젝이 드디어 마무리가 되었다. 상반기 지원이 얼마 남지 않은 만큼 담주부터 꼭 코테를 꾸준하게 풀 수 있도록 하자
> 푼 문제
- [백준 #2169. 로봇 조종하기](https://www.acmicpc.net/problem/2169): DP/ 골드2
- [백준 #20056. 마법사 상어와 파이어볼](https://www.acmicpc.net/problem/20056): 구현/ 골드4
- [백준 #1520. 내리막길](https://www.acmicpc.net/problem/1520): DP/ 골드3
---
정리한 링크: (바로가기)
```python
"""
https://www.acmicpc.net/problem/1520
"""
import sys
#0. 맵 (N,M) 칸 별 탐사 가치 설정
N , M = map(int,input().split()) # y,x 
fields =list()
for n in range(N) :
fields.append(list(map(int, input().split())))
dp = [[0 for _ in range(M)] for k in range(N)]
left2right = [[0 for _ in range(M)] for k in range(N)]
right2left = [[0 for _ in range(M)] for k in range(N)]
#3.탐색 가능  (1)left2 right <-/ (2) right2left <- 
for m in range(M) : …
```

[BOJ]#1520 test 

---

minjeong/test.txt

> **제출한 코드**와 **TIL, WIL**은 꼭 작성해주기!
- 
> 푼 문제
- [백준 #12345. 테스트](https://www.acmicpc.net/problem/1541): 그래프 / 실버2
---
정리한 링크: (바로가기)
```python
```
> 배운 점이 있다면 입력해주세요
-

test: test코드 추가 8

---

minjeong/test.txt

> **제출한 코드**와 **TIL, WIL**은 꼭 작성해주기!
- 
> 푼 문제
- [백준 #2345. 잃어버린 괄호](https://www.acmicpc.net/problem/1541): 그래프 / 실버2
---
정리한 링크: (바로가기)
```python
```
> 배운 점이 있다면 입력해주세요
-

test: test코드 추가 9

---

learntosurf/test_commit.md

> **제출한 코드**와 **TIL, WIL**은 꼭 작성해주기!
- 
> 푼 문제
- [백준 #1234. 잃어버린 괄호](https://www.acmicpc.net/problem/1234): DP / 실버2
- [백준 #2345. 잃어버린 괄호](https://www.acmicpc.net/problem/2345): DP / 실버2
- [백준 #3456. 잃어버린 괄호](https://www.acmicpc.net/problem/3456): DP / 실버2
- [백준 #4567. 잃어버린 괄호](https://www.acmicpc.net/problem/4567): 그래프 / 실버2
- [백준 #5678. 잃어버린 괄호](https://www.acmicpc.net/problem/5678): 그래프 / 실버2
- [백준 #6789. 잃어버린 괄호](https://www.acmicpc.net/problem/6789): 그래프 / 실버2
---
정리한 링크: (바로가기)
```python
```
> 배운 점이 있다면 입력해주세요
-

test PR #5

---

minjeong/test.txt

> **제출한 코드**와 **TIL, WIL**은 꼭 작성해주기!
- 
> 푼 문제
- [백준 #2345. 잃어버린 괄호](https://www.acmicpc.net/problem/1541): 그래프 / 실버2
---
정리한 링크: (바로가기)
```python
```
> 배운 점이 있다면 입력해주세요
-

test: test코드 추가 10 (찐막)
