minjeong/Backtracking/2024-03-04-[백준]-#15650-N과M(2).py, minjeong/Backtracking/2024-03-04-[백준]-#15651-N과M(3).py, minjeong/Backtracking/2024-03-05-[백준]-#15652-N과M(4).py, minjeong/Backtracking/2024-03-06-[백준]-#9663-NQueen.py, minjeong/HashMap/2024-03-10-[Programmers]-귤 고르기.py, minjeong/Math/2024-03-07-[Programmers]-피보나치 수.py, minjeong/Sort/2024-03-09-[Programmers]-최솟값만들기.py, minjeong/Stack, Queue/2024-03-08-[Programmers]-올바른괄호.py, minjeong/String/2024-03-07-[Programmers]-최솟값과 최댓값.py
- N과 M 시리즈
- N Queen
- 매번 자주 사용하는 `sort`
- 정작 역순 정렬할 때는 자꾸 어떻게 써야 할 지 까먹는다.
- `sort(reverse=True), sorted(reverse=True`
- **파이썬의 역순 정렬 ( `reverse()` / `reversed()` )**
- `list.reverse()` **: list 자체를 역순으로 정렬, 함수 반환값 None 값**
- `reversed(list)` : 역순 정렬된 list 새로운 변수에 할당 가능
딕셔너리 정렬이 가물가물했다. 딕셔너리 정렬을 하면 좋을 것 같다고 생각이 들었는데, 딕셔너리는 key-value이니까 정렬을 못한다는 기억이 언저리 있었다.
하지만 딕셔너리도 key기준으로 또는 value를 기준으로 오름차순/내림차순 정렬을 할 수 있었다.
다음과 같이 `sorted()`를 이용하여 dict를 정렬할 수 있다.
`sorted()`에 인자로 `my_dict.items()`를 전달하면 오름차순으로 정렬됨
```python
my_dict = {'c': 3, 'a': 1, 'b': 2, 'e': 1, 'd': 2}
sorted_dict = sorted(my_dict.items())
print(sorted_dict)
```
`sorted()`는 다음과 같이 Tuple pair로 이루어진 List를 리턴함
```python
[('a', 1), ('b', 2), ('c', 3), ('d', 2), ('e', 1)]
```
참고로, `my_dict.items()`를 출력해보면 다음과 같이 Tuple pair로 이루어진 …
=> minjeong / 3월 2주차 / 9문제

minjeong/Backtracking/2024-03-13-[백준]-#14888-연산자 끼워넣기.py, minjeong/Backtracking/2024-03-15-[백준]-#14889-스타트와 링크.py, minjeong/Stack, Queue/2024-03-12-[PGS]-캐시.py, minjeong/String/2024-03-16-[Programmers]-#뉴스클러스터링.py
- 푼 문제들의 플로우를 담았습니다. 문제 정리 열심히 했습니다.
1. [PGS] 캐시 (성공)
2. [PGS] 뉴스 클러스터링 (성공)
3. [BOJ] #14888. 연산자 끼워넣기 (힌트보고 겨우 성공)
4. [BOJ] #14889. 스타트와 링크  (실패)
[문제 정리 링크 바로 가기](https://minggirokkk.notion.site/9de8b73a60c84deab4a3ca06a02a399d?pvs=4)
- LRU라고 하였으므로, 큰 틀은 FIFO와 같이 처리되도록 하되, 한 번 사용된 것은 제거하고 다시 맨 뒤에 보내도록 한다. FIFO처럼 처리하기 위해서 deque 자료구조를 사용한다.
1. deque 자료구조인 `cache`를 초기화한다. 정답으로 반환할 `totalTime`도 초기화한다.
6. `cities`의 길이만큼 반복하여, 각 `city`를 처리한다.
1. `city`는 대소문자 구분이 아니므로 모두 lowercase로 바꿔준다.
2. `cacheSize`가 0인 경우에는 따로 예외처리를 해주도록 한다.
7. `cache` 안에 `city`가 있는지 확인한다. 만약 있다면, 해댱 `city`를 제거한 후 다시 맨 뒤에 append한다. (최신으로 갱신) 또 cache hit이므로 `totalTime`에 1을 더한다.
만약 없다면, cache miss이므로 `totalTime`에 5를 더한다. 그리고 가장 앞에 있는 것을 pop하고, 해당 `city`를 맨 뒤에 추가한다.
- 이때, `cache`가 `cacheSize` 크기가 되고 `cacheSize`가 0이 아닐 때에는 다시 …
=> Minjeong / 3월 3주차 / 4문제

JYP/도키도키 간식드리미.py, JYP/카드 2.py, JYP/큐 2.py
**큐 2: 큐 기능을 직접 구현하는 문제**
1. sys로 명령 수를 받은 뒤, deque를 통해 비어 있는 큐를 생성한다
2. 기능에 대한 설명은 문제에 명시되어 있어 먼저 기능부터 구현하였다 (push, pop, size, empty, front, back)
3. 이후 입력된 명령 수인 a 만큼 입력 b를 받으며 for문 반복
```
import sys
a = int(sys.stdin.readline())
deq = deque()
for _ in range(a):
b = sys.stdin.readline().split()
if b[0] == 'push':
deq.append(int(b[1]))
if b[0] == 'pop':
if deq:
print(deq.popleft())
else:
print(-1)
if b[0] == 'size':
print(len(deq))
if b[0] == 'empty':
if deq:
print('0')
else:
print('1')
if b[0] == 'front':
if deq:
print(deq[0])
else:
print(-1)
if b[0] == 'back':
if deq:
print(deq[-1])
else:
print(-1)
```
**카드 2: 마지막 남은 카드 번호 구하는 문제**
1. 먼저 카드의 개수를 불러온 뒤, deque함수를 이용해 빈 큐를 생성한다
2. 이후, for문을 통해 1부터 a까지의 수(카드 번호)를 큐에 넣는다
3. 이후 popleft()함수를 사용하여 deq의 길이가 1이 될 …
=> JYP / 3월 4주차 / 3문제

minjeong/DynamicProgramming/2024-03-25-[백준]-#1932-정수삼각형.py, minjeong/DynamicProgramming/2024-03-27-[백준]-#1149-RGB거리.py, minjeong/DynamicProgramming/2024-03-28-[백준]-#2579-계단오르기.py, minjeong/DynamicProgramming/2024-03-29-[백준]-#2156-포도주시식.py
>푼 문제
- [백준 #1932. 정수 삼각형](https://www.acmicpc.net/problem/1932): DP 실버1
- [백준 #1149. RGB 거리](https://www.acmicpc.net/problem/1149) : DP, 실버1
- [백준 #2569. 계단 오르기](https://www.acmicpc.net/problem/2569): DP, 실버3
- [백준 #2156. 포도주 시식](https://www.acmicpc.net/problem/2156): DP, 실버1
[정리 링크 바로가기](https://minsllogg.tistory.com/entry/BOJ-1932-%EC%A0%95%EC%88%98%EC%82%BC%EA%B0%81%ED%98%95-Python-DP)
1. 어떻게 동작 과정이 수행되는지 핸드트레이싱해본다.
2. 리스트를 어떻게 받아낼지 아이디어를 떠올린다.
이 2가지 과정을 거쳤다.
1. 어떻게 동작 과정이 수행되는지 핸드트레이싱해본다.
⇒ 대각선 왼쪽, 대각선 오른쪽만 이동할 수 있다. 
이때, 양쪽 끝에 있는 부분은 그냥 그대로 내려받는다.
그게 아니라면, max()를 이용해서 양쪽으로 내려오는 것들 중 더했을 때 더 큰 값을 다시 저장하도록 한다.
1. 리스트를 어떻게 받아낼 것인가?
가장 간단한 방법은 중첩 리스트를 이용하는 것이다.
```python
[[7], [3, 8], [8, 1, 0], [2, 7, 4, 4], [4, 5, 2, 6, 5]]
```
중첩리스트를 다시 한 번 살펴보자
```python
[[7],
[3, 8], 
[8, 1, 0], …
```
=> Minjeong / 3월 5주차 / 4문제

JYP/덱 2.py, JYP/요세푸스 문제 0.py, JYP/풍선 터뜨리기.py
- 입력 a, b를 받은 뒤 1 ~ a까지의 수를 queue에 입력한다
- 큐의 모든 원소가 꺼내질때까지 while문을 반복하는데, b번째 사람을 제거하기 위해 큐를 b-1번 왼쪽으로 이동시킨다
- 이후 제거된 순으로 res에 append 후  res를 출력한다
```
queue = deque()
res = []
a, b = map(int, input().split())
for i in range(1, a+1):
queue.append(i)
while queue:
for i in range(b-1):
queue.append(queue.popleft())
res.append(queue.popleft())
print("<",end='')
for i in range(len(res)-1):
print("%d, "% res[i], end='')
print(res[-1], end='')
print(">")
```
- 자료구조 deque를 이용
- 값이 양수인 경우 시계 방향으로 이동하며, 음수인 경우에는 절대값만큼 시계 반대 방향으로 이동한다
- 풍선의 갯수 (n)을 전달받은 후 for문을 통해 n번 반복하게 된다
- for문이 반복되는 동안 popleft를 통해 deque 내부의 가장 왼쪽 원소(터뜨릴 풍선) 및 인덱스를 가져온 뒤, 해당 원소의 값에 따라 회전을 진행하며 풍선을 터뜨린다
- 이후 풍선이 터진 순서대로 출력한다
```
import sys
n = int(sys.stdin.readline()) …
```
=> JYP / 3월 5주차 / 3문제

minjeong/DynamicProgramming/2024-04-01-[백준]-#11053-가장긴증가하는부분수열.py, minjeong/DynamicProgramming/2024-04-04-[백준]-#2565-전깃줄.py, minjeong/DynamicProgramming/2024-04-05-[백준]-#11726-2xn타일링.py, minjeong/DynamicProgramming/2024-04-06-[백준]-#9095-123_더하기.py
목표 유형: DP (증말 어려웠다..;😵;)
> 푼 문제
- [백준 #11053. 가장 긴 증가하는 부분 수열](https://www.acmicpc.net/problem/11053): DP 실버2
- [백준 #2565. 전깃줄](https://www.acmicpc.net/problem/2565) : DP, 골드5
- [백준 #11726. 2xn타일링](https://www.acmicpc.net/problem/11726): DP, 실버3
- [백준 #9095. 1,2,3 더하기](https://www.acmicpc.net/problem/90954): DP, 실버3
정리한 노션 링크: [노션](https://minggirokkk.notion.site/11053-f300eb3a4ac740e09549cdcee0187492?pvs=4)
이 문제를 풀다보니 다른 방식으로 접근하는 것은 다 ‘틀렸습니다’라고 처리한다. 
그렇다면 정말 제대로 DP를 사용해야 한다는 것. DP에 무엇을 저장해야 할 지부터 정리해야 한다. 그 내용은 문제에 잘 나와있다. 문제에서 정답을 출력하는 것은 가장 긴 수열의 ‘길이’이다.
따라서 dp에도 수열의 길이를 저장하면 된다.
위의 Institution을 토대로 아래와 같은 flow를 세울 수 있다.
1. `n`과 `n`만큼의 길이의 `A` 리스트를 입력받는다.
2. 이중for문을 통해서 `A[i] > A[j]`라면 `dp[i]`값을 증가시킨다.
1. i값을 `j`는 `0 ~ i-1`까지 확인 후, 가장 큰 …
=> Minjeong / 4월 1주차 / 4문제

JYP/queuestack.py, JYP/팩토리얼 2.py
- 스택은 LIFO 형태를 갖고 있기에 따로 처리할 부분이 없어 스택 부분은 무시하고 여러개의 큐를 하나의 큐로 생각해 풀어나가면 되는 문제이다
- 문제의 입력으로 0(큐) / 1(스택)으로 받으나 스택 부분을 무시하고 큐만을 사용하여 원하는 결과를 얻을 수 있다
```
import sys
a = int(input())
sec1 = list(map(int, input().split()))  # 0 or 1
sec2 = list(map(int, input().split()))
b = int(input())
sec3 = list(map(int, input().split()))
queue = deque([])
for i in range(a):
if sec1[i] == 0:
queue.appendleft(sec2[i])
else:  
if queue == []:
print(*sec3)
sys.exit()
for j in range(b):
queue.append(sec3[i])
print(queue.popleft(), end = " ")
```
=> JYP / 4월 2주차 / 2문제

minjeong/DynamicProgramming/2024-04-10-[백준]-#11055-가장큰증가하는부분수열.py, minjeong/DynamicProgramming/2024-04-14-[백준]-#9251-LCS.py, minjeong/Stack, Queue/2024-04-08-[Programmers]-#짝지어_제거하기.py
---
name: 민정 PR 템플릿
about: '알고리즘 '
---
목표 유형: DP 
-> 푼 문제
- [PGS ##짝지어 제거하기](https://school.programmers.co.kr/learn/courses/30/lessons/12973): 스택/큐 Level 2
- [백준 #11055. 가장 큰 증가하는 부분수열](https://www.acmicpc.net/problem/11055): DP 실버2
-  [백준 #9251. LCS](https://www.acmicpc.net/problem/9251): DP 골드5
---
정리한 노션 링크: [노션](https://minggirokkk.notion.site/870a5741e4fe40ce8bcb8d9bd0f416ef?pvs=4)
`짝`을 찾아야 한다? 그러면 스택이 답이다. 
그래서 이 문제는 스택이겠구나 싶었다. 
*~~(하지만 처음 접근할 때는 맨날 DP풀다가 오랜만에 스택 문제를 접해서, 다른 길로 샜다…)~~*
*~~(그래서 다른 길로 세서 잘못 시간초과가 나왔던 코드와, 스택으로 접근한 코드 모두 기록했다.)~~*
스택으로 접근하려면 2가지를 고려해야 한다. 
1. 언제 push할 것인가?
2. 언제 pop할 것인가?
---
1. **언제 push할 것인가?**
⇒ pop하지 않을 경우에는 모두 추가한다.
또는 stack에 아무것도 없다면 추가한다. (왜냐하면, 초기에 아무것도 없는데 pop해버리면 indexError가 발생하기 때문에 stack이 …
=> Minjeong / 4월 2주차 / 3문제

minjeong/BitMasking/2024-04-25-[백준]-#11723-집합.py, minjeong/DFSBFS/2024-04-28-[백준]-#1012-유기농배추.py, minjeong/Graph/2024-04-28-[백준]-#1012-유기농배추.py, minjeong/Greedy/2024-04-24-[백준]-#1641-잃어버린괄호.py, minjeong/PrefixSum/2024-04-26-[백준]-#11659-구간합구하기4.py, minjeong/PrefixSum/2024-04-27-[백준]-#2559-수열.py
> **푼 문제**
- [백준 #1541. 잃어버린 괄호](https://www.acmicpc.net/problem/1541): 그리디 / 실버2
- [백준 #11723. 집합](https://www.acmicpc.net/problem/11723): 비트마스킹 / 실버5
- [백준 #11659. 구간 합 구하기4](https://www.acmicpc.net/problem/11659): 누적합(prefix Sum)/ 실버3
- [백준 #2559. 수열](https://www.acmicpc.net/problem/2559): 누적합(prefix Sum) / 실버3
- [백준 #1012. 유기농 배추](https://www.acmicpc.net/problem/1012): DFSBFS/ 실버2
---
정리한 노션 링크: [노션](https://minggirokkk.notion.site/1541-f18c2ff7731a471a880879854d592441?pvs=4)
- `-`를 기준으로 나눈다(=괄호를 친다)
- 이후 `+`를 기준으로 나누고 연산을 진행한다
- 그 이후 `-` 연산을 진행한다
> 예시: 3 + 10 - 5 - 8 + 24 
⇒ 3 + 10 - 5 - ( 8 + 24 ) = 8 - 31 = -23
> 
1. `-`를 기준으로 나눈다.
`3+10` `5` `8+24` 
2. 이후 `+` 기준으로 나누어 연산을 진행한다
`13` `5` `31`
3. 그 다음 각 문자열간 `-` 연산을 진행한다
`13` `-` `5` …
=> Minjeong / 4월 4주차 / 5문제

minjeong/Greedy/2024-05-13-[PGS]-#체육복.py, minjeong/Greedy/2024-05-15-[PGS]-#구명보트.py, minjeong/Greedy/2024-05-17-[백준]-#1931-회의실배정.py
> 문제 유형: 그리디
> **푼 문제**
- [PGS 체육복](https://school.programmers.co.kr/learn/courses/30/lessons/42862#): 그리디 / Level1
- [PGs 구명보트](https://school.programmers.co.kr/learn/courses/30/lessons/42885): 그리디 / Level2
- [백준 #1931. 회의실 배정](https://www.acmicpc.net/problem/1931): 그리디 / 실버1
---
정리한 노션 링크: [노션](https://minggirokkk.notion.site/406ec8b535724ed38d47f06e9d55773c?pvs=4)
테스트케이스를 통해서 문제에서 접근하는 방법을 정리해보자
1. `lose`리스트와 `reserve` 리스트에 공통으로 들어간 번호는 여벌 체육복을 가져왔는데 도난을 당한 경우이다. 즉, 도난은 당했지만 남은 체육복이 1개이기 때문에 수업에는 참여할 수 있으나 체육복은 빌려줄 수 없다. 따라서 `lost` 와 `list` 에서 모두 지워줘야 한다.
2. `n`번의 학생이 체육복을 안 가져왔다면, `n-1`이나 `n+1`번 학생한테만 빌릴 수 있다.
3. 위 과정을 거쳤다면 `lost`와 `reserve`는 `index`순서대로 하나씩 비교하게 된다.
> 💡 **당면한 문제점**
for문 안에서 remove를 하니까 remove를 한 시점에서 반복이 종료된다.
```python …
```
=> Minjeong / 5월 3주차 / 3문제

minjeong/Divide&Conquer/2024-07-30-[백준]-#2630-색종이만들기.py, minjeong/Divide&Conquer/2024-08-02-[백준]-#1074-Z.py, minjeong/Divide&Conquer/2024-08-04-[백준]-#1992-쿼드트리.py, minjeong/Math/2024-08-01-[PGS]-#점프와순간이동.py
> 푼 문제
-  [백준 #2630. 색종이 만들기](https://www.acmicpc.net/problem/2630): 분할정복, 재귀 / 실버2
-  [프로그래머스 #점프와 순간 이동](https://school.programmers.co.kr/learn/courses/30/lessons/12980): 수학 / Level 2
- [백준 #1074. Z](https://www.acmicpc.net/problem/1074): 분할정복, 재귀 / 실버1
- [백준 #1992. 쿼드트리](https://www.acmicpc.net/problem/1992): 분할정복, 재귀 / 실버1
---
정리한 링크: ([바로가기](https://minggirokkk.notion.site/2630-12eb29180ddf4d94ae2350c98d5f3d76?pvs=4))
1. 종이의 크기 `n`과 정사각형의 칸의 색을 입력받아 `colored_paper` 리스트에 저장한다.
2. 하얀색 색종이의 개수는 `white_cnt`로, 파란색 색종이의 개수는 `blue_cnt`로 각각 0으로 초기화한다.
3. `find_number_of_paper` 함수는 색종이의 색을 분할정복하여 재귀적으로 파악하는 함수이다. `x_start`, `y_start`부터 시작하는 `nxn` 크기의 종이가 모두 같은 색인지 파악한다.
1. 하얀색 종이의 경우, 모두 더하면 0이다. 따라서 범위 내에서 모두 더한 값이 0이라면 `white_cnt`의 값을 증가시킨다.
2. 파란색 색종이의 경우, 1을 n*n번 …
=> Minjeong / 7월 5주차 / 4문제

minjeong/DFSBFS/2024-11-05-[백준]-#2644-촌수계산(BFS).py, minjeong/DFSBFS/2024-11-05-[백준]-#2644-촌수계산(DFS).py, minjeong/DFSBFS/2024-11-06-[백준]-#18352-특정거리의도시찾기.py, minjeong/DFSBFS/2024-11-06-[백준]-#7562-나이트의이동.py, minjeong/DFSBFS/2024-11-07-[백준]-#25195-Yes_or_yes.py, minjeong/DFSBFS/2024-11-07-[백준]-#2573-빙산.py, minjeong/DFSBFS/2024-11-08-[백준]-#7569-토마토.py, minjeong/DynamicProgramming/2024-11-10-[백준]-#14916-거스름돈(DP).py, minjeong/Graph/2024-11-04-[백준]-#3665-최종순위.py, minjeong/Greedy/2024-11-09-[백준]-#27961-고양이는많을수록좋다.py, minjeong/Greedy/2024-11-10-[백준]-#14916-거스름돈(그리디).py
> 푼 문제
- [백준 #3665. 최종 순위](https://www.acmicpc.net/problem/3665): 위상정렬 / 골드1
- [백준 #2644. 촌수계산](https://www.acmicpc.net/problem/2644): DFSBFS / 실버2
- [백준  #7562. 나이트의 이동](https://www.acmicpc.net/problem/7562): DFSBFS / 실버1
- [백준 #18352. 특정 거리의 도시 찾기 ](https://www.acmicpc.net/problem/18352): DFSBFS / 실버2
- [백준 #25195. Yes or yes](https://www.acmicpc.net/problem/25195): DFSBFS / 골드4
- [백준 #2573. 빙산](https://www.acmicpc.net/problem/2573): DFSBFS / 골드4
- [백준 #7569. 토마토](https://www.acmicpc.net/problem/7569): DFSBFS / 골드5
- [백준 #27961. 고양이는 많을수록 좋다 ](https://www.acmicpc.net/problem/27961): 그리디 / 브론즈1
- [백준 #14917. 거스름돈](https://www.acmicpc.net/problem/14917): 그리디 / 실버5
---
정리한 링크: ([바로가기](https://minjeong.oopy.io/134dded9-d6ea-804d-bde8-f696822be058))
1. **초기 설정**
1. …
=> Minjeong / 11월 2주차 / 9문제

minjeong/Greedy/2024-11-12-[백준]-#13417-카드문자열.py, minjeong/Greedy/2024-11-13-[백준]-#2847-게임을_만든_동준이.py, minjeong/Greedy/2024-11-14-[백준]-#2212-센서.py, minjeong/Greedy/2024-11-14-[백준]-#31926-밤양갱.py, minjeong/Greedy/2024-11-15-[백준]-#1374-강의실.py
> 푼 문제
- [백준 #13417. 카드 문자열](https://www.acmicpc.net/problem/13417): 그리디, 문자열, 덱 / 실버3
- [백준 #2847. 게임을 만든 동준이](https://www.acmicpc.net/problem/2847): 그리디 / 실버4
- [백준 #31926.  밤양갱](https://www.acmicpc.net/problem/31926): 그리디 / 실버1
- [백준 #2212. 센서](https://www.acmicpc.net/problem/2212): 그리디 / 골드5
- [백준 #1374. 강의실](https://www.acmicpc.net/problem/1374): 그리디, 힙 / 골드5
---
정리한 링크: ([바로가기](https://minjeong.oopy.io/13bdded9-d6ea-809d-8661-ce10bb038524))
> 해결전략
- **특정 한 카드를 기준으로 하지 않고, 매번 새로운 카드를 가져올 때마다 현재 문자열의 가장 앞 글자와 비교**하여 알파벳을 맨 왼쪽이나 오른쪽에 배치해야 한다.
*~~(난 비록, 가장 첫 카드가 기준이 되는 건 줄 알고, 틀렸다만..)~~* 
- 가져온 카드가 현재 문자열의 가장 앞 글자보다 작거나 같으면 **왼쪽**에, 그렇지 않으면 **오른쪽**에 배치한다.
- 리스트에서 맨 앞에 있는 값을 가져와야 하므로 `deque` 자료형과 `popleft` 함수를 활용한다.
1. 테스트케이스 수 `t`만큼 아래 과정을 반복한다.
2. 카드 개수 …
=> Minjeong / 11월 3주차 / 5문제

minjeong/DynamicProgramming/2024-12-14-[백준]-#10844-쉬운계단수.py, minjeong/DynamicProgramming/2024-12-14-[백준]-#1914-하노이탑.py, minjeong/PrefixSum/2024-12-10-[백준]-#11660-구간합구하기5.py, minjeong/Simulation/2024-12-14-[백준]-#14500-테트로미노.py
- 이번 주에는 너무 바빠서 코테 문제 푸는 게 너무 빡셌다.. 시간 내는 게 중요한 것 같다. 또 TIL이나 내용 정리를 많이 못했는데 다음 주에는 제대로 할 수 있도록 시간을 꼭 내야겠다.
- 계속 DP만 풀다가 오랜만에 구현, DFS 문제를 푸니까 헷갈리고 어려웠다.. 여러 문제를 골고루 푸는 것도 중요한 것 같다. 
> 푼 문제
- [백준 #11660. 구간 합 구하기 5 ](https://www.acmicpc.net/problem/11660): DP / 실버1
- [백준 #10844. 쉬운 계단 수](https://www.acmicpc.net/problem/10844): DP / 실버1
- [백준 #1914. 하노이탑](https://www.acmicpc.net/problem/1914): DP / 실버1
- [백준 #14500. 테트로미노](https://www.acmicpc.net/problem/14500): 구현 / 골드4
---
1. **입력 처리:**
- 숫자 표 크기 `N`, 쿼리 수 `M` 입력받는다.
- 숫자 표를 입력받아 `grid` 배열 생성한다.
2. **누적합 테이블 계산:**
- `prefix_sum[i][j]`를 점화식을 통해 계산한다.
3. **범위 합 계산:**
- 각 쿼리에 대해 주어진 범위를 누적합 공식으로 계산한다.
```python
import sys
def get_prefix_sum(grid, N):
prefix_sum = [[0] …
```
=> Minjeong / 12월 2주차 / 4문제

minjeong/DynamicProgramming/2024-12-30-[백준]-#15681-트리와쿼리.py, minjeong/DynamicProgramming/2024-12-30-[백준]-#1949-우수마을.py, minjeong/Simulation/2025-01-02-[백준]-#2563-색종이.py, minjeong/Simulation/2025-01-03-[백준]-#25206-너의평점은.py, minjeong/Simulation/2025-01-04-[백준]-#5430-AC.py
**1. 트리 DP**
- 트리 구조에서 DP(동적 계획법)를 적용하는 문제를 처음 풀어봤는데, **DFS와 DP를 동시에 사용하는 방식이 신선**하게 다가왔다.
- 트리 DP 문제를 해결할 때는 DFS 결과를 저장해 재사용하는 것이 핵심이며, **자식 노드의 방문 여부를 정확하게 체크하는 것이 중요**하다.
- 이 과정을 통해 트리 문제에 대한 이해가 깊어지고, 새로운 영역으로의 확장감을 느낄 수 있었다.
**2. 구현 문제**
- 실버 난이도 2개와 골드 난이도의 문제 1개를 풀었다.
- 문제를 해결하며 리스트 슬라이싱과 형변환 과정이 **O(N)**의 시간복잡도를 갖는다는 점을 새롭게 알게 되었다.
- 또한, `deque` 자료형에 `reverse()` 함수가 존재한다는 점도 이번에 배운 흥미로운 부분이었다.
**3. 회고**
- 매번 느끼는 점이지만, **문제를 정확하게 읽고 해석하는 것**의 중요성을 다시금 깨달았다.
- 이번 주에는 입출력 조건을 놓쳐서 문제를 잘못 풀이하는 실수를 범했다.
- 이와 더불어,**주어진 조건을 조합하는 능력뿐만 아니라, 이를 효율적으로 구현하는 능력도 중요하다는 점**을 체감했다.
다음과 같은 프로세스를 자주 연습하고 습관화해야겠다고 다짐했다.
1. 필수 기능을 먼저 체크하고, **주기능**을 중심으로 전체 틀 구성
2.  주요 기능을 보완하는 **부가적인 요소**들을 하나씩 채워나가기
3. **입출력 조건**을 정확하게 반영하여 코드 작성
4. 코드 완성 후 **비효율적인 부분을 개선**해 최적화
⇒ 이러한 프로세스를 …
=> Minjeong / 1월 1주차 / 5문제

minjeong/DynamicProgramming/2025-01-07-[PGS]-단어퍼즐.py, minjeong/DynamicProgramming/2025-01-07-[PGS]-올바른괄호의갯수.py, minjeong/Greedy/2025-01-11-[백준]-#16953-A→B.py, minjeong/Simulation/2025-01-10-[백준]-#17413-단어뒤집기2.py, minjeong/Stack, Queue/2025-01-08-[백준]-#1874-스택수열.py
- 이번 주에는 프로그래머스에서 스킬체크 Level 4 문제를 풀었다. 2문제 모두 DP 문제였다. 평소에 풀던 DP는 규칙성이 쉽게 보여서 DP 유형이 쉽다고 생각했었는데, Level 4에서의 DP는 규칙성이 보이지 않아 많이 헤맸었다. DP 문제를 풀면서 `카탈란 수`를 알게 되었다. 처음에는 `카탈란 수`가 무엇인지 어떻게 이러한 규칙이 생기게 된 것인지 이해가 가지 않았다. 이제야 다양한 DP 무제를 풀어야 하는 이유를 이해할 수 있게 되었다. DP 문제를 풀며 그 안에 주로 사용되는 수학적 공식이나 점화식을 알아두는 것이 나중에 도움이 될 것 같다.
- 문제를 풀면서  `deque` 타입이나 리스트를 복사하고 싶을 때 바로 대입했었는데 그러면 새로 복사되는 것이 아니라 참조하게 되어 내가 원하는대로 코드가 동작하지 않다는 것을 알게 되었다. 특히 deque 타입을 복사하고 싶다면 `queue.copy()`를 사용하거나 `deque(queue)`로 새로운 `deque`를 생성해야 한다는 점을 알게 되었다. 
> 푼 문제
- [프로그래머스 단어 퍼즐](https://school.programmers.co.kr/learn/courses/30/lessons/12983?language=python3): DP / Level4
- [프로그래머스 올바른 괄호의 갯수](https://school.programmers.co.kr/learn/courses/30/lessons/12929?language=python3): DP / Level4
- [백준 #1874. 스택 …
=> Minjeong / 1월 2주차 / 5문제

_WeeklyChallenges/W12-[DP]/Assignment_BOJ_1520_내리막길.py, learntosurf/Dynamic Programming/2025-02-17-[BOJ]-#2169-로봇조종하기.py, learntosurf/Dynamic Programming/2025-02-23-[BOJ]-#1520-내리막길.py
- DP 문제를 발제하면서 풀이방법을 다시 익힐 수 있었다. 정답 풀이를 보면 쉬워보이는데 풀땐 어려운 DP의 세계...
- 다음주는 꼭 하루에 1문제씩 문제 풀고 정리할것!! 
- [백준 #2169. 로봇 조종하기](https://www.acmicpc.net/problem/2169): DP / 골드2
- [백준 #1520. 내리막길](https://www.acmicpc.net/problem/1520): DP / 골드3
---
- **DP 테이블 정의**
`dp[i][j]`: (i,j) 좌표까지 도달할 때 탐사한 지역 가치의 최대 합 
- **DP 점화식 구성 (경로 선택)** 
어떤 좌표 (i,j)에 도달하는 방법은 세 가지 이다.
- 위(↓)에서 오는 경우: `dp[i-1][j]`
- 왼쪽(←)에서 오는 경우: `dp[i][j-1]`
- 오른쪽(→)에서 오는 경우: `dp[i][j+1]`
하지만, 한 번 탐사한 지역은 다시 올 수 없으므로, 경로를 구하는 방법이 다르다.
[예제]
- **첫번째 행(`i=0`)은, 왼쪽에서 오른쪽으로 진행하는 경우밖에 없다.** (왔던 칸을 다시 못오기 때문에)
→ 하나씩 값을 누적한 값이 그 칸에 도달하는 최대가치가 된다.
- 나머지 행들은 순서대로 탐색하여 좌표값들을 업데이트한다.
→ 두번째 행(`i=1`)부터는 왼쪽/오른쪽을 나누어 각 좌표의 최대가치를 업데이트할 수 있다.
- 이때, 각 행들은 **두가지 임시배열(왼쪽→오른쪽으로 진행시 구해진 최대값, 오른쪽→왼쪽으로 진행시 구해진 최대값)로 표현한다.**
- 왼쪽→오른쪽(`left_to_right`): …
=> Learntosurf / 2월 3주차 / 2문제 

.github/workflows/update_challenge_progress.yml, _MonthlyChallenges/extract_pr_data.py, _MonthlyChallenges/update_dashboard.py, _MonthlyChallenges/update_scoreboard.py
- **매달 투표**로 정한 2개의 알고리즘 유형(예: 그래프, DP)을 각각 5문제 이상 풀면 상품 제공
- **수작업 집계의 번거로움**: 누가 뭘 풀었는지 일일이 확인하고 기록하는 게 너무 귀찮았습니다.
- **실시간 피드백 부족**: PR을 올린 후에도 팀원들이 현재 진행 상황을 바로 알기 어려웠습니다.
- **PR 템플릿**에 문제 정보를 입력하면, 자동으로 문제 데이터를 추출(`extract_pr_data.py`)
- 사용자별, 유형별 문제 집계 및 달성 여부 업데이트(`update_scoreboard.py`)
- 최신 진행 상황을 Markdown 형식의 대시보드 파일(`DASHBOARD.md`)로 업데이트하고, 이전 달 기록은 `HISTORY.md`에 보관
- 변경된 내용은 자동으로 커밋되고, PR에 최신 진행 상황 코멘트로 반영
이번 자동화 시스템은 다음과 같이 구성되어 있습니다:
1. **PR 템플릿과 데이터 추출**
- 스터디원이 PR을 생성할 때, 문제 정보를 특정 템플릿에 맞춰 작성합니다.
- `extract_pr_data.py` 스크립트가 PR 본문에서 문제 정보와 작성자 정보를 파싱하여 `pr_data.json` 파일에 저장합니다.
2. **스코어보드 업데이트**
- `update_scoreboard.py` 스크립트는 `pr_data.json` 파일의 데이터를 읽어 사용자별, 챌린지 유형별로 문제 번호를 집계합니다.
- 사용자별 데이터는 반드시 scoreboard 파일 내 `"users"` 키에 저장되며, 각 사용자가 해당 챌린지의 목표(문제 5개 이상)를 달성했는지 여부도 …
=> Feat:  챌린지 진행 관리 자동화

learntosurf/test_commit.md
- 주어진 시간 내에 푸는 것도 중요하지만, 우선 혼자 힘으로 풀어내기 위해서 훈련을 하고 있다는 걸 기억하기! 
- 이번주차 발제/과제 문제들을 아직 잘 이해하지는 못한것 같다. 풀이를 다시 정리하고 비슷한 문제를 몇번 더 풀어보면 좋을 것 같다. 
> 푼 문제
- [백준 #5582. 공통 부분 문자열](https://www.acmicpc.net/problem/5582): DP / 골드5
- [백준 #20542. 받아쓰기](https://www.acmicpc.net/problem/20542): DP / 골드3
- [백준 #2776.암기왕](https://www.acmicpc.net/problem/2776): 그래프 / 실버4
- [백준 #1654. 랜선 자르기](https://www.acmicpc.net/problem/1654): 그래프 / 실버2
- [백준 #11663. 선분 위의 점](https://www.acmicpc.net/problem/11663): 그래프 / 실버3
- [백준 #2343. 기타 레슨](https://www.acmicpc.net/problem/2343): DP / 실버1
---
정리한 링크: (바로가기)
```python
import sys 
S1 = list(input().strip())
S2 = list(input().strip()) 
n, m = len(S1), len(S2)
dp = [[0] * (m+1) for _ in range(n+1)]
max_len = 0
for i in range(1, n+1):
for j in …
```
=> test PR #3

YoonYn9915/dp/2025-04-10-[백준]-#10844-쉬운 계단 수.py, YoonYn9915/dp/2025-04-12-[백준]-#1562-계단 수.py, YoonYn9915/recursion/2025-04-10-[백준]-#1780-종이의 개수.py
- 쉬운 계단 수 문제도 그렇고 계단 수문제도 그렇고 dp를 잘 안다고 생각했는데 이해가 잘 안됐다... dp배열에 자리수 n과 마지막 숫자 i를 기록하는 것과 0과 9는 앞에 한 개만(각각 1, 8) 올 수 있고 2-8은 앞에 두 개가 올 수 있다는 것도 알았는데 점화식 규칙을 왜 못찾았는지 잘 모르겠다. 계단 수 문제는 비트마스킹을 사용한다는 것이 새로웠다. 풀다가 좀 피곤해서 이런 문제가 코테 나올까 싶었는데 현대 소프티어에 이런 유형이 나와서 좀 피곤했다. 암튼 계단 수 문제는 못풀어서 꼭 다시 풀어야 될거 같다 
> 푼 문제
- [백준 #10844. 쉬운 계단 수](https://www.acmicpc.net/problem/10844): DP / 실버1
- [백준 #1780. 종이의 개수](https://www.acmicpc.net/problem/1780): 재귀 / 실버2
- [백준 #1562. 계단수](https://www.acmicpc.net/problem/1562): DP / 골드1
---
정리한 링크: ([바로가기](https://purple-jury-c2d.notion.site/1b01eff69e9e805da1d7e4928d8e9d52?pvs=4))
```python
N = int(input())
dp = [[0] * 10 for _ in range(N + 1)]
for i in range(1, 10):
dp[1][i] = 1
for i in range(2, N + 1):
for j in range(10):
if j == 0:
dp[i][j] = …
```
=> YoonYn9915 / 4월 2주차 / 3문제

minjeong/DynamicProgramming/2025-04-07-[백준]-#10844-쉬운계단수.py, minjeong/DynamicProgramming/2025-04-09-[백준]-#1562-계단수.py, minjeong/DynamicProgramming/2025-04-10-[백준]-#2193-이친수.py, minjeong/DynamicProgramming/2025-04-12-[백준]-#2302-극장좌석.py
- 정말 오랜만에 코테 문제를 풀이했다. 지난 주 스킬체크도 그렇고 스터디할 때도 그렇고 너무 오랫동안 안 푸니까 뇌가 굳는 느낌이었다. 앞으로 다시 심기일전해서 꾸준히 풀어야겠다.
- 이번 주는 DP 문제를 풀이했다. 그 중에서도 가장 기억에 남는 건 `계단수` 문제와 `극장좌석` 문제이다. 
- `계단수` 문제의 경우 `비트마스킹`을 사용한다는 것이 새로웠다. 비트마스킹은 이론적으로는 아는 개념인데 이를 DP에 어떻게 적용하는지가 관건이었고 어려운 부분이었다. 이 문제를 통해서 `<<` 연산자가 언제, 왜 쓰이는지를 이번 기회에 정확히 알 수 있었다.
- `극장좌석` 문제의 경우, 문제의 겉모습에서는 전혀 피보나치 수열의 규칙성이 보이지 않지만 조금 더 들여다보면 피보나치 수열이 사용되는 것이 놀라웠다. 피보나치 수열의 가능성을 다른 문제를 풀 때도 열어둬야겠다. 또한 VIP 좌석을 기준으로 구간을 나누고, 각 구간의 경우의 수를 따로 구해 곱하는 방식은 다른 문제에도 응용할 수 있을 것 같다.
- 다음 주에는 DP 문제도 풀고, 그래프 문제도 풀어야겠다. ~DP만 풀다가 다시 그래프 봤을 때 하나도 못 풀까봐 조금 걱정된다~
> 푼 문제
- [백준 #10844. 쉬운 계단 수](https://www.acmicpc.net/problem/10844): DP / 실버1
- [백준 #2193. 이친수](https://www.acmicpc.net/problem/2193): DP / 실버3
- [백준 #1562. …
=> Minjeong / 4월 2주차 / 4문제

YoonYn9915/backtracking/2025-04-14-[백준]-#1759-암호 만들기.py, YoonYn9915/greedy/2025-04-18-[백준]-#13305-주유소.py, YoonYn9915/implementation/2025-04-19-[백준]-#6603-로또.py
- 이번 한주는 백트래킹, 그리디, 조합 중에서 가장 기본적이고 간단한 문제를 풀어봤다. 여기저기 면접도 다니고 지원서도 쓰느라 알고리즘 공부는 잘 안하게 되는 면이 있어서 앞으로는 쉽고 빠르게 풀수 있는 간단한 문제를 위주로 풀려고 한다. 이제 이정도 문제는 힌트 안보고 빠른 시간안에 풀 수있게 되어서 알고리즘 동아리 했던 지난 9개월이 실력 향상에 많은 도움이 된 거 같다고 느낀다!
> 푼 문제
- [백준 #1759. 암호 만들기](https://www.acmicpc.net/problem/1759): 그래프 / 골드 5
- [백준 #13305. 주유소](https://www.acmicpc.net/problem/13305): 그리디 / 실버 3
- [백준 #6603. 로또](https://www.acmicpc.net/problem/6603): 그리디 / 실버 2
---
정리한 링크: ([바로가기](https://purple-jury-c2d.notion.site/1d81eff69e9e80eabf82c004a9b8e957?pvs=4))
```python
def check_password(password):
num_vowel = sum(1 for c in password if c in 'aeiou')
num_consonant = len(password) - num_vowel
return num_vowel >= 1 and num_consonant >= 2
def recursion(start, depth, password):
if depth == L:
if …
```
=> YoonYn9915 / 4월 3주차 / 3문제

learntosurf/Backtracking/2025-04-19-[BOJ]-#15649-N과M(1).py, learntosurf/Backtracking/2025-04-19-[BOJ]-#6603-로또.py
**rebase을 잘못한 걸 수습한다고 PR을 따로 분리해서 올리면서 이전 커밋이 날라갔습니다.,,, 
발제 문제 커밋이 그래서 이전 PR에 포함되었어요,,, 번거로우시겠지만 코멘트가 있으면 다른 곳에 남겨주시면 감사하겠습니다!!** 
- 이번 스터디 발제 문제를 풀면서 백트래킹 유형이 처음이라는 것을 알게 되었다. 발제 문제 풀이를 들으면서까지는 정확히 어떤 느낌인지 잘 와닿지는 않았는데 조건 있는 완전탐색이라고 보면 되는 건가 라는 느낌으로 이해했다. 종료조건을 꼭 정의하고, 선택하지 않은 경우의 수를 탐색하고, 선택을 계속 반영해주는 것이 특징인 것 같다. 다른 기본 문제들을 같이 풀어봐야겠다. 
```python
def backtrack(상태):
if 종료조건(상태):
정답 처리
return
for 선택 in 가능한 선택들:
if 유효하지 않은 선택:
continue
상태에 선택 추가
backtrack(업데이트된 상태)
선택 되돌리기 (상태 복구)
```
- 매주 한 주제씩은 개념+기본문제+발제/과제 난이도 문제를 정리하면서 가고 싶은데 매번 작심N일이다(근데 이제 N이 3이하일때...). 다음주는 백트래킹이나 DP 문제 유형을 풀어보고싶다! 실버 문제들을 많이 풀어보고 힌트 없이 쓱쓱 풀어낼 수 있게 만들고 싶다. 일단 꾸준히 하기 🫠
> 푼 문제
- [백준 #1759. 암호 만들기](https://www.acmicpc.net/problem/1759): 백트래킹 / 골드5
- [백준 #6603. 로또](https://www.acmicpc.net/problem/6603): 백트래킹 / 실버2
- …
=> Learntosurf / 4월 3주차 / 3문제

YoonYn9915/binary search/2025-04-18-[백준]-#2470-두 용액.py, YoonYn9915/binary search/2025-04-26-[백준]-#2473-세 용액.py, YoonYn9915/dp/2025-04-26-[백준]-#2240-자두 나무.py
- 이번 주는 투 포인터 혹은 이분탐색과 관련된 문제를 발제했다. 이전에도 부분합, 블랙 프라이데이 등의 문제로 이 주제를 접했었는데, 그때마다 힌트없이는 못 풀었었다. 근데 코테에 자주 나오는 유형은 아니라고 해서 dp, 그래프, 구현, 그리디 등의 문제를 더 중요시 했었는데 이번 코테 풀 때 나와서 복습 차 이 주제를 선정했다. 
-  과제 문제를 어떻게 풀까... 하다가 
1. 발제 문제에서 풀었던 대로 합의 절댓값이 0에 가장 가까운 두 용액을 먼저 구한 후 나머지 용액 중 절댓값이 가장 작은 용액을 골라서 3개를 맞추자 라고 생각했는데 `[-2 6 -97 -6 98]에서 [6, -6, -2]`를 골라버리면서 (6과 -6의 합이 0이니까 이것을 우선 뽑고 나머지 중 가장 작은 -2를 뽑은 로직) 실패.
2. 세 개의 포인터(`left`, `mid`, `right`)를 써서 left와 right 사이에 모든 값을 하나씩 mid로 지정하여 비교해가며 풀이했는데, 문제를 풀다 보니 이 방법은 O(N2)으로 시간 초과로 실패.
3. 그러다보니 힌트를 써서 세 값을 구해야 할 때는 하나의 값을 고정(`i`)하고, 나머지 두 값을 투포인터로 찾아야 한다는 것을 알게 되었다. 쉬운 로직이었는데 풀때는 왜 생각이 안난건지 모르겠다.
> 푼 문제
- [백준 #2470. 두 용액](https://www.acmicpc.net/problem/2470): 투 포인터 / 골드 5
- [백준 #2473. 세 …
=> YoonYn9915/ 4월 4주차/ 3문제

Hongjoo/백준/김밥천국의계단.py, Hongjoo/백준/두용액.py, Hongjoo/백준/세용액.py
- 이번 주는 목표한 양의 문제를 다 풀지 못하였다. 실버 1~ 골드는 여전히 풀고 정리하는데만 4시간 걸리는 것 같다. 풀면서 다른 사람들은 이걸 어떻게 1시간 내로 아이디어를 떠올리고 푸는지 신기할 따름이다. 
- 담주 부터는 꼭 매일 풀도록 하자 
> 푼 문제
- [백준 #2470. 두 용액](https://www.acmicpc.net/problem/2470): 투포인터 / 골드 5
- [백준 #28069. 김밥천국의 계단](https://www.acmicpc.net/problem/28069): DP / 골드 5
- [백준 #2473. 세 용액](https://www.acmicpc.net/problem/2473): 투포인터 / 골드3
---
정리한 링크: ([바로가기](https://zaqquum01.notion.site/BOJ-2470-1dc9899f253f80c2a767c5ad6411abce?pvs=4))
1. 오름차순 정렬
2. 투 포인터 → right , left 의 합의 절대값이 작은 조합 찾기
```python
import sys
N = int(sys.stdin.readline())
liqs = sorted(list(map(int, sys.stdin.readline().split())))
start = 0 ; end = len(liqs)-1
closed_z = [start,end,abs(liqs[start] + liqs[end])]
while start < end :
c = liqs[start] + liqs[end]
if closed_z[-1] > …
```
=> HONGJOO / 4월 4주차 /3개

YoonYn9915/binary search/2025-05-03-[백준]-#1654-랜선 자르기.py, YoonYn9915/dp/2025-05-03-[백준]-#1149-RGB거리.py, YoonYn9915/dp/2025-05-03-[백준]-#1912-연속합.py
- 이번 한 주는 몸이 안좋아서 정신이 없었다. 이제 java로 코테 준비하기 시작했는데 오랜만에 하다보니 많이 까먹어서 어려운 난이도의 문제를 풀지 못할거 같았다. 그래서 당분간 실버 문제 위주로 풀면서 java 프로그래밍 좀 다시 익힐 예정.  
> 푼 문제
- [백준 #1912. 연속합](https://www.acmicpc.net/problem/1912): DP / 실버 2
- [백준 #1149. RGB거리](https://www.acmicpc.net/problem/1149): DP / 실버 1
- [백준 #1654. 랜선 자르기](https://www.acmicpc.net/problem/1654): 이분탐색 / 실버 2
---
정리한 링크: [바로가기](https://purple-jury-c2d.notion.site/1e81eff69e9e80a89ebee6256c60e88c?pvs=4)
```python
n = int(input())
arr = list(map(int, input().split()))
dp = [0] * n
dp[0] = arr[0]
for i in range(1, n):
dp[i] = max(arr[i], dp[i-1]+arr[i])
print(max(dp))
```
---
정리한 링크: [바로가기](https://purple-jury-c2d.notion.site/RGB-1e81eff69e9e803aa5bcfbe5f520e9e8?pvs=4)
```python
n = int(input())
cost = …
```
=> YoonYn9915/ 4월 5주차/ 3문제

minjeong/BinarySearch/2025-04-28-[백준]-#2110-공유기설치.py, minjeong/BinarySearch/2025-05-01-[백준]-#1654-랜선자르기.py, minjeong/DFSBFS/2025-05-02-[백준]-#2178-미로탐색.py, minjeong/DFSBFS/2025-05-02-[백준]-#2667-단지번호붙이기.py
> 이번 한 주의 소감을 작성해주세요! 
- 이번 주에는 발제 문제로 이분 탐색, 그 중에서도 `매개변수 탐색`에 대해 알게 되었다. 기존 이진 탐색은 정렬된 값 중에서 특정 원소를 찾는 방식이었다. 하지만 이 문제는 정답이 될 수 있는 "범위 내 값"을 이진 탐색으로 좁혀가야 했다. 처음에는 이게 너무 헷갈렸는데 이런 문제를 풀어볼 수 있어서 정말 다행이라는 생각이 들었다. 관련 문제를 많이 풀어서 내걸로 만들어야겠다.
- `단지번호붙이기` 문제에서는 "플러드 필"이라는 개념을 새로 알게 되었다. `미로 탐색` 문제도 풀면서 오랜만에 그래프 문제인 BFS 문제를 풀게 되었다. DFS로 접근해야 할 지, BFS로 접근해야 할 지 헷갈리는 게 좀 있었지만 문제들을 풀면서 다시 리마인드 하게 되었다.
- 이번 달(5월)에는 코테도 많아서 진짜 지금보다 더 많이 연습해야 할 것 같다. 이번 주는 살짝 뒷전이었던 코테연습.. 다음 주부터는 진짜 빡시게 해야겠다.
> 푼 문제
- [백준 #2110. 공유기 설치](https://www.acmicpc.net/problem/2110): 이분탐색 / 골드4
- [백준 #1654. 랜선 자르기](https://www.acmicpc.net/problem/1654): 이분탐색 / 실버2
- [백준 #2178. 미로 탐색](https://www.acmicpc.net/problem/2178): 그래프 / 실버1
- [백준 #2667. 단지번호 붙이기](https://www.acmicpc.net/problem/2667): 그래프 / 실버1
---
정리한 링크: (바로가기)
> 코드를 …
=> Minjeong / 4월 5주차 / 4문제

minjeong/BinarySearch/2025-05-05-[백준]-#2512-예산.py, minjeong/Simulation/2025-05-12-[백준]-#1283-단축키지정.py, minjeong/Simulation/2025-05-16-[백준]-#2564-경비원.py, minjeong/Stack, Queue, Priority Queue/2025-05-10-[Programmers]-올바른괄호(JAVA).java, minjeong/Stack, Queue, Priority Queue/2025-05-12-[Programmers]-기능개발-java.java, minjeong/Stack, Queue, Priority Queue/2025-05-12-[Programmers]-프로세스-java.java, minjeong/Stack, Queue, Priority Queue/2025-05-14-[PGS]-같은숫자는싫어(java).java, minjeong/String/2025-05-07-[PGS]-전화번호목록.java
- `발제&과제` 문제는 "구현"과 관련한 문제였다. 구현 문제는 쉽게만 생각했는데 이번 문제들은 실버1이었음에도 굉장히 애를 먹었다. 조건도 제대로 설정해줘야 했고, 고려해야 할 사항이 많았다. **하지만 정말 중요한 건 문제의 내용을 제대로 파악하고 이해하는 것이었다.** `발제&과제` 문제 모두 문제를 대충 읽다가 문제 풀이 중반부에 잘못되었다는 것을 알게 되었다. `과제` 문제의 경우 사각형 경계선을 1차원으로 단순화하는 발상이 인상깊었다. 이렇게 사고할 수도 있구나 알게 되었다.
- 그 외의 문제들로는 `Java`로 코테 문제 풀이하는 것을 연습하기 위해 `스택/큐` 유형을 `Java`로 푸는 연습을 했다. 초반에는 파이썬에 익숙하다보니 같은 문제더라도 어떻게 구현해야 할 지 감이 아예 오지 않았다. 문제를 풀이하면서 `import java.util.*;`  를 해야 한다는 점, 타입을 매번 지정해줘야 한다는 점, 파이썬이랑 함수가 다르다는 점, Array와 ArrayList의 함수가 다르다는 점, ArrayList로 한 후 다시 Array로 형태를 바꾸는 코드를 꼭 추가해야 한다는 점, DTO를 활용한다는 점  등등 정말 기본적인 문법들을 문제를 풀이하면서 익히게 되었다. 
- [백준 #2512. 예산](https://www.acmicpc.net/problem/2512): 이분탐색 / 실버2
- [프로그래머스 #42577. 전화번호 목록](https://school.programmers.co.kr/learn/courses/30/lessons/42577?lang …
=> Minjeong / 5월 2주차 / 8문제

YoonYn9915/Graph/2025-05-19-[백준]-#7576-토마토.py, YoonYn9915/Graph/2025-05-24-[백준]-#7569-토마토.py, YoonYn9915/implementation/2025-05-24-[백준]-#16509-장군.py
- 이번 주는 그래프 유형, 정확히는 BFS, 골드 난이도 3문제를 풀어보았다. 세 문제 다 방향성은 금방 잡혔는데, 잔실수가 많아서 좀 시간을 오래 썼다. 7569번 문제는 오랫만에 3차원 리스트를 썼는데, arr[x축][y축][z축]형태로 썼다가 디버깅 하느라 한참 헤맸다. 그래도 확실히 이제는 문제 유형을 파악하고 구현 방법을 생각해내는게 어렵지는 않았다.
> 푼 문제
- [백준 #7576. 토마토](https://www.acmicpc.net/problem/7576): 그래프 / 골드 5
- [백준 #7569. 토마토](https://www.acmicpc.net/problem/7569): 그래프 / 골드 5
- [백준 #16509. 장군](https://www.acmicpc.net/problem/16509): 그래프 / 골드 5
---
정리한 링크: [(바로가기)](https://purple-jury-c2d.notion.site/1fd1eff69e9e80cd9030c49d3b0a2eb1?pvs=4)
```python
import sys
inp = sys.stdin.readline
M, N = map(int, inp().split())
arr = []
visited = [[-1] * M for _ in range(N)]
for _ in range(N):
arr.append(list(map(int, inp().split())))
def find_tomato(arr, visited):
tomatoes = []
for …
```
=> YoonYn9915 /  5월 3주차/ 3문제

_WeeklyChallenges/W23-[BFS]/Assignment_BOJ_7569_토마토.py
5월 3주차 과제 문제 풀이 업로드합니다
[바로가기](https://github.com/AlgorithmStudy-Allumbus/codingtest_algorithm_study/tree/main/_WeeklyChallenges/W23-%5BBFS%5D)
=> feat: 5월 3주차 과제 문제 풀이 업로드

YoonYn9915/implementation/2025-05-29-[백준]-#11559 Puyo Puyo.py
- 이번 한 주 면접 3개가 잡혀있어서 알고리즘 공부 할 시간이 적었다. 과제문제는 풀어야 할 것 같아서 어떻게든 풀었다.
> 푼 문제
- [백준 #11559. Puyo Puyo](https://www.acmicpc.net/problem/11559): 그래프 / 골드 4
---
정리한 링크: [(바로가기)](https://purple-jury-c2d.notion.site/Puyo-Puyo-2051eff69e9e8063a5fef1740a0251d4?source=copy_link)
```python
from sys import stdin
input = stdin.readline
EMPTY = '.'
dx = (1, -1, 0, 0)
dy = (0, 0, 1, -1)
def delete_block():
for x, y in blocks:
board[x][y] = EMPTY
def update_board():
for y in range(6):
for t in range(10, -1, -1):
for x in range(11, t, -1):
if board[x][y] == EMPTY and board[t][y] != EMPTY:
board[x][y], board[t][y] = board[t][y], EMPTY
def is_in_area(x, y):
return 0 <= x < 12 and 0 <= y < 6
def bfs(x, y):
queue = deque([(x, y)])
visited[x][y] = True …
```
=> YoonYn9915/ 5월 4주차 / 1문제

minjeong/DFSBFS/2025-05-26-[백준]-#16509-장군.py, minjeong/DFSBFS/2025-05-31-[백준]-#11559-PuyoPuyo.py, minjeong/Heap/2025-05-31-[PGS]-더맵게(java).java
- 이번 한 주는 새로 시작한 부트캠프에 적응하느라 많은 문제를 풀지는 못했다... 
- 발제와 과제 문제로 `BFS+구현` 문제를 풀었고, 다른 문제로는 java로 힙 유형 문제를 풀이해보았다.  BFS 구현 문제의 경우, 큰 틀은 다 동일한 것 같다. 다만 방향이라거나, 맵이 이동한다거나 추가적인 조건을 다루는 것이 어려운 부분인 것 같다. `#16509 장군 문제`도 방향이 8가지나 되어 이동하는 걸 고려하는 것이 가장 헷갈렸던 부분이었다. `#11559. Puyo Puyo` 는  중력을 처리하는 부분이 막막했다. Puyo가 터지게 되면 밑으로 내려오도로 하기 위해서 반복적으로 교환하며 풀이하는 부분이 인상적이었다. 나의 경우, 이 부분에서 막혀서 다른 분들의 정답을 보고 풀이를 이어가게 되었다.
- Java로 풀이한 `프로그래머스 고득점 kit - 더 맵게` 문제의 경우, Java에서 `Heap`을 구현하기 위해서는 `PriorityQueue`를 사용하면 된다는 것을 알게 되었다.
> 푼 문제
- [백준 #16509. 장군](https://www.acmicpc.net/problem/16509): 그래프 / 골드5
- [백준 #11559. Puyo Puyo](https://www.acmicpc.net/problem/11559): 그래프 / 골드4
- [프로그래머스 #42626. 더맵게](https://school.programmers.co.kr/learn/courses/30/lessons/42626?language=java): 힙 / Level2
---
정리한 …
=> Minjeong / 5월 4주차 / 3문제

Hongjoo/lv2/멀리뛰기.py, Hongjoo/백준/뿌요뿌요.py, Hongjoo/백준/장군.py, Hongjoo/백준/토마토.py
- 정말 오랜만에 문제 할당량을 채운 것 같다. 이제 슬슬 인턴 지원으로 노선을 바꿨기 때문에 다시 알고리즘 공부할 때가 된 것 같다. 하반기 및 인턴 대비해서 이번 다가오는 6월 안에 꼭 프로그래머스 lv2 에서 벗어나도록 하자
> 푼 문제
- [백준 #11559. 뿌요뿌요](https://www.acmicpc.net/problem/11559): 그래프 / 골드4
- [백준 #11559. 장군](https://www.acmicpc.net/problem/16509): 그래프 / 골드4
- [백준 #11559. 토마토](https://www.acmicpc.net/problem/7576): 그래프 / 골드4
- [프로그래머스 #12914.멀리뛰기](https://school.programmers.co.kr/learn/courses/30/lessons/12914): Backtracking / lv2
---
정리한 링크: ([바로가기](https://zaqquum01.notion.site/11559-2049899f253f80389280cdde25de8266?pvs=4))
1. 해당 turn에서 전체 field 속 뿌요뿌요가 있는 위치 확인
1-2) BFS로 같은 색상의 뿌요가 4개 이상 연결되있는지 확인하기
-BFS로 연결 개수 확인
-만약,  4개 이상이면 field 에서  비우고(.) , 변환 flag 을 True 변환
1-3) 전체 field 돌고 나서 flag = True (한 번이라도 터지면 )이면  
⇒ 전체 field …
=> HONGJOO/ 5월 4주/ 4개

YoonYn9915/2025-06-07-[백준]-#1715-카드 정렬하기.py, YoonYn9915/Graph/2025-06-07-[백준]-#1388-바닥 장식.py, YoonYn9915/greedy/2025-06-03-[백준]-#14698-전생했더니 슬라임 연구자였던 건에 대하여 (Hard).py
- 발제 문제와 과제 문제 풀면서 이런 유형에 대한 자신감이 생긴것 같다. 한번 익숙해지고 풀이방법이 떠오르니까 과제문제 푸는데는 30분도 안걸렸다. 다른 유형 풀다보면 잊어버릴까봐 걱정이다.
> 푼 문제
- [백준 #14698 전생했더니 슬라임 연구자였던 건에 대하여 (Hard)](https://www.acmicpc.net/problem/14698): 그리디 / 골드 4
- [백준 #1388. 바닥 장식](https://www.acmicpc.net/problem/1388): 그래프 / 실버 4
- [백준 #1715. 카드 정렬하기](https://www.acmicpc.net/problem/1715): 그리디 / 골드 4
---
정리한 링크: (바로가기)
```python
import heapq
import sys
inp = sys.stdin.readline
MOD = 1000000007
test_case = int(inp())
for _ in range(test_case):
N = int(inp())
arr = list(map(int, inp().split()))
if N == 1:
print(1)
continue
hq = []
for num in arr:
heapq.heappush(hq, num)
result = 1
while len(hq) > 1:
a = heapq.heappop(hq)
b = heapq.heappop(hq)
energy = a * b
result = (result * energy) % MOD
heapq.heappush(hq, energy) …
```
=> YoonYn9915/ 6월 1주차/ 3문제

minjeong/DFSBFS/2025-06-16-[백준]-#14226-이모티콘.py, minjeong/DFSBFS/2025-06-21-[백준]-#13549-숨바꼭질3.py, minjeong/Greedy/2025-06-22-[프로그래머스]-키패드누르기.py
- 이번 주에는 **BFS로 다양하게 탐색하는 방법을 배운 한 주였다.** 발제 문제와 숨바꼭질 시리즈가 비슷하여 BFS를 더 연습해볼 수 있었던 것 같다. 문제마다 조건들이 있는데 해당 조건들에 어려워하지말고 **분기 처리**하면 된다는 것을 알게 되었다. 또 무엇보다 **범위값**을 잘 지정해야 한다. 
- `과제` 문제에서는 0-1 BFS 유형을 알게 되었다. `0-1 BFS`를 구현하기 위해서는 우선순위가 높은 것은 (deque 기준으로) appendleft로 우선 탐색할 수 있도록 해주어야 한다는 것을 알게 되었다. 
- 따로 푼 그리디 유형의 `키패드 누르기` 문제는 Level1이었지만 처음에 문제의 아이디어를 내기까지는 부끄럽지만 조금 시간이 걸렸다. 하지만 정말 단순하게 풀면 되는 문제였다.
> 푼 문제
- [백준 #14226. 이모티콘](https://www.acmicpc.net/problem/14226): 그래프 / 골드4
- [프로그래머스 #67256. 키패드 누르기](https://school.programmers.co.kr/learn/courses/30/lessons/67256): 그리디 / Level 1
- [백준 #13549. 숨바꼭질3](https://www.acmicpc.net/problem/13549): 그래프 / 골드5
---
정리한 링크: ([바로가기](https://minsllogg.tistory.com/entry/%EB%B0%B1%EC%A4%80-14226-% …
=> Minjeong / 6월 3주차 / 3문제

YoonYn9915/dijkstra/2025-06-23-[백준]-#1504-특정한 최단 경로.py, YoonYn9915/dijkstra/2025-06-28-[백준]-#1753-최단 경로.py, YoonYn9915/implementation/2025-06-28-[백준]-#15905-스텔라가 치킨을 선물했어요.py
- 몇 넌 전에 알고리즘 수업 들을때 다익스트라는 생각도 안하고 바로 손코딩 가능했었는데, 문제 안 푼지 한 6개월 되니까 다익스트라 고민하다 제한 시간이 끝났다. 따로 알고리즘 유형을 공부해서 정리하지는 않았는데 너무 잘 까먹어서 해야 하나 생각중이다. 주중에는 피곤하니까 이번 주말부터 하나씩 시작.. 
> 푼 문제
- [백준 #1504. 특정한 최단 경로](https://www.acmicpc.net/problem/1504): 그래프, 다익스트라 / 골드 4
- [백준 #1753. 최단 경로](https://www.acmicpc.net/problem/1753): 그래프, 다익스트라 / 골드 4
- [백준 #15905. 스텔라가 치킨을 선물했어요](https://www.acmicpc.net/problem/15905): 구현 / 실버 5
---
정리한 링크: (바로가기)
```python
import sys
import heapq
INF = float('inf')
N, E = map(int, input().split())
graph = [[] for _ in range(N + 1)]
for _ in range(E):
a, b, c = map(int, input().split())
graph[a].append((b, c))
graph[b].append((a, c))
v1, v2 = map(int, input().split())
def dijkstra(start, end):
dist = [INF] * (N + 1) …
```
=> YoonYn9915 / 6월 4주차 / 3문제

YoonYn9915/implementation/2025-07-12-[백준]-#17204-죽음의 게임.py, YoonYn9915/implementation/2025-07-12-[백준]-#17269-이름궁합 테스트.py, YoonYn9915/implementation/2025-07-12-[백준]-#20436-ZOAC 3.py
- 이번 주 간단한 구현 문제 위주로 풀었다. 크게 어려운 점은 없었고 시간이 없어서 티어가 낮은 문제들 위주로 풀어서 그런지 크게 느낀 점은 없었다. 
- [백준 #17204. 죽음의 게임](https://www.acmicpc.net/problem/17204): 구현 / 실버 3
- [백준 #17269. 이름궁합 테스트](https://www.acmicpc.net/problem/17269): 구현 / 실버 5
- [백준 #20436. ZOAC3](https://www.acmicpc.net/problem/20436): 구현 / 실버 5
---
정리한 링크: (바로가기)
```python
N, K = map(int, input().split())
num_list = [int(input()) for _ in range(N)]
point = 0  # 지목을 하는 사람 (0부터 시작)
M = 0       # 지목 횟수(M번째 지목)
for i in range(N):
target = num_list[point]    # target: 지목당한 사람
M += 1                      # 지목했으니까 카운트 1 증가
if target == K:
print(M)
break
point = target    # 지목당한 사람이 이제는 지목하는 사람이 됨
else:
print(-1)
```
---
정리한 링크: (바로가기)
```python
import copy
dic = …
```
=> YoonYn9915 / 7월 2주차 / 3문제

minjeong/Backtracking/2025-07-21-[백준]-#15683-감시.py, minjeong/Backtracking/2025-07-22-[백준]-#16987-계란으로계란치기.py, minjeong/DFSBFS/2025-07-14-[PGS]-타겟넘버(java).java, minjeong/DFSBFS/2025-07-18-[PGS]-게임맵최단거리(java).java
- 이번 주에는 주로 DFS, 백트래킹, BFS 유형 위주로 풀이했다. 솔직히 너무 풀기 싫었지만,, 풀다 보면 정말 많이 배울 수 있는 유형인 것 같다.
- 몇몇 문제는 Java로도 풀이했다. 파이썬이 훨씬 편했다는 걸 더 느끼게 되었다. 그래도 이런 식으로 몇몇 문제는 자바로 푸는 연습을 꾸준히 하는 게 좋을 것 같다.
> 푼 문제
- [프로그래머스 #43165. 타겟 넘버(java)](https://school.programmers.co.kr/learn/courses/30/lessons/43165): 그래프 / Level 2
- [백준 #15683. 감시 - 백트래킹](https://www.acmicpc.net/problem/15683): 구현 / 골드3
- [프로그래머스 #1844. 게임 맵 최단거리(java)](https://school.programmers.co.kr/learn/courses/30/lessons/1844): 그래프 / Level 2
- [백준 #16987. 란으로 계란치기 - 백트래킹](https://www.acmicpc.net/problem/16987): 구현 / 골드5
---
정리한 링크: (바로가기)
1. 정답의 개수를 저장할 전역 변수 `count`를 0으로 초기화한다.
2. `backtracking()` 함수에서는
1. 매 단계마다 두 가지 (+ 더하기, - 빼기) 선택을 재귀적으로 수행한다.
2. 만약 모든 숫자를 순회했을 경우 종료한다.
- 이때 현재 합계와 target값이 같을 경우 …
=> Minjeong / 7월 4주차 / 4문제

YoonYn9915/Graph/2025-07-14-[프로그래머스]-#92342-양궁대회.py, YoonYn9915/Graph/2025-07-28-[프로그래머스]-#81302-거리두기.py, YoonYn9915/Graph/2025-08-02-[백준]-#2468-안전영역.py, YoonYn9915/greedy/2025-08-02-[백준]-#1026-보물.py
- 점점 알고리즘에 신경을 못 쓰는 느낌..  
> 푼 문제
- [프로그래머스 #81302. 거리두기](https://school.programmers.co.kr/learn/courses/30/lessons/81302): 그래프 / level 2
- [백준 #2468. 안전영역](https://www.acmicpc.net/problem/2468): 그래프 / 실버 1
- [백준 #1026. 보물](https://www.acmicpc.net/problem/1026): 그리디 / 실버 4
---
정리한 링크: (바로가기)
```python
def bfs(places, i, j, k):
queue = deque()
queue.append((j, k, 0))  # row, col, dist
visited = [[False] * 5 for _ in range(5)]
visited[j][k] = True
dx = [-1, 1, 0, 0]
dy = [0, 0, -1, 1]
while queue:
row, col, dist = queue.popleft()
if dist != 0 and places[i][row][col] == 'P':
return 1
if dist == 2:
continue
for d in range(4):
nr = row + dx[d]
nc = col + dy[d]
if 0 <= nr < 5 and 0 <= nc < 5 and not visited[nr][nc]: …
```
=> YoonYn9915 / 7월 5주차 / 3문제 

Hongjoo/백준/요세푸스문제.py, Hongjoo/백준/타노스는요세푸스가밉다.py
- 이번 주는 날씨가 더워서 그런지(?) 코딩 권태기가 온 듯 하다. 다음 주 부터는 꼭 루틴 지켜서 1일1문제를 달성하도록 하겠습니다. 
> 푼 문제
- [백준 #1158. 요세푸스](https://www.acmicpc.net/problem/1158): 큐 / 실버4
- [백준 #280633. 타노스는 요세푸스가 밉다.](https://www.acmicpc.net/problem/1541): 큐 / 실버2
---
정리한 링크: ([바로가기](https://zaqquum01.notion.site/1158-2459899f253f80709413e0f33668c3ac?source=copy_link))
1. K-1 씩 오른쪽으로 포인터를 이동하여 pop & answer에 추가
2.출력
```python
import sys
N , K = map(int , sys.stdin.readline().split())
#1. 원형 큐 만들기 
elements = [i for i in range(1,N+1)]
answer = []
p = 0 
while elements : 
p = (p + K-1) % len(elements)
answer.append(elements.pop(p))
#2.출력 
print("<"+", ".join(list(map(str, answer))) + ">")
```
정리한 링크: …
=> Hongjoo/8월 1주차 /2문제

Hongjoo/lv2/가장큰정사각형찾기.py, Hongjoo/백준/blobaww.py, Hongjoo/백준/lcs.py, Hongjoo/백준/결혼식.py, Hongjoo/백준/그림.py, Hongjoo/백준/평범한배낭_2t.py
- 이번 주는 LCS나 냅샙문제 등 DP의 대표적인 문제 유형들을 풀어보았다. 여전히 문제 속 규칙 찾고 점화식을 세우는 과정까지가 어렵지만 이제는 DP 문제가 등장해도 어렵지 않게 접근 할 수 있을 것 같다. 
> 푼 문제
- [프로그래머스 #12905. 가장 큰 정사각형 찾기](https://school.programmers.co.kr/learn/courses/30/lessons/12905): DP / level2
- [백준 #1926. 그림](https://www.acmicpc.net/problem/1926): 그래프/ 실버1
- [백준 #5567. 결혼식](https://www.acmicpc.net/problem/5567): 그래프/ 실버2
- [백준 #24501. blobaww](https://www.acmicpc.net/problem/24501): DP/ 골드3
- [백준 #9251. LCS](https://www.acmicpc.net/problem/9251): DP/ 골드5
- [백준 #12865. 평범한 배낭_2try](https://www.acmicpc.net/problem/12865): DP/ 골드5
---
정리한 링크: ([바로가기](https://www.notion.so/zaqquum01/2609899f253f8007960ce110e54b306c?v=64891ffb6f324b5c853e1b2695dd8497&source=copy_link))
- if board[i][j] == 1 이면
-> dp[i,j] = min( (i-1,j), (i,j-1) …
=> Hongjoo/ 9월 1주차 / 6문제
